### ISSUE TITLE
[BUG] Not starting transcription/upload 

### ISSUE THREAD

**Issue by oschmidteu** [pluja/whishper#100]
## **Description**
I have to same problem like he does:
https://github.com/pluja/whishper/issues/17#issuecomment-1704054061
I can "start" but no file will be uploaded nor is anything visible on the frontend. 
![30353213-3E47-436D-B43D-4AE528836929](https://github.com/pluja/whishper/assets/13415307/6fd6fbc1-f0bb-4804-aa75-7020c01642f7)

### **To Reproduce**
Start a new Transcription and 

### **Expected behavior**
Transcription is added/visible on the frontend

### Environment
- OS: Linux/Synology
- Browser: Edge
- Version: [e.g., 22]
- Hosting: NAS/Synology

### Docker Compose Logs
```
whisper-libretranslate  | Updating language models
whisper-libretranslate  | Found 88 models
whisper-libretranslate  | Keep 4 models
whisper-libretranslate  | Downloading English → French (1.9) ...
whisper-libretranslate  | Downloading English → Spanish (1.0) ...
whisper-libretranslate  | Downloading French → English (1.9) ...
whisper-libretranslate  | Downloading Spanish → English (1.0) ...
whisper-libretranslate  | Loaded support for 3 languages (4 models total)!
whisper-libretranslate  | Running on http://*:5000
whishper-postgres-1     | The files belonging to this database system will be owned by user "postgres".
whishper-postgres-1     | This user must also own the server process.
whishper-postgres-1     | 
whishper-postgres-1     | The database cluster will be initialized with locale "en_US.utf8".
whishper-postgres-1     | The default database encoding has accordingly been set to "UTF8".
whishper-postgres-1     | The default text search configuration will be set to "english".
whishper-postgres-1     | 
whishper-postgres-1     | Data page checksums are disabled.
whishper-postgres-1     | 
whishper-postgres-1     | fixing permissions on existing directory /var/lib/postgresql/data ... ok
whishper-postgres-1     | creating subdirectories ... ok
whishper-postgres-1     | selecting dynamic shared memory implementation ... posix
whishper-postgres-1     | selecting default max_connections ... 100
whishper-postgres-1     | selecting default shared_buffers ... 128MB
whishper-postgres-1     | selecting default time zone ... Etc/UTC
whishper-postgres-1     | creating configuration files ... ok
whishper-postgres-1     | running bootstrap script ... ok
whishper-postgres-1     | performing post-bootstrap initialization ... ok
whishper-postgres-1     | syncing data to disk ... ok
whishper-postgres-1     | 
whishper-postgres-1     | 
whishper-postgres-1     | Success. You can now start the database server using:
whishper-postgres-1     | 
whishper-postgres-1     |     pg_ctl -D /var/lib/postgresql/data -l logfile start
whishper-postgres-1     | 
whishper-postgres-1     | waiting for server to start....2024-05-27 10:31:31.514 UTC [49] LOG:  starting PostgreSQL 16.3 (Debian 16.3-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
whishper-postgres-1     | 2024-05-27 10:31:31.666 UTC [49] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
whishper                | 2024-05-27 10:31:45,133 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
whishper                | 2024-05-27 10:31:45,231 INFO supervisord started with pid 1
whishper                | 2024-05-27 10:31:46,233 INFO spawned: 'backend' with pid 7
whishper                | 2024-05-27 10:31:46,234 INFO spawned: 'frontend' with pid 8
whishper                | 2024-05-27 10:31:46,236 INFO spawned: 'nginx' with pid 9
whishper                | 2024-05-27 10:31:46,238 INFO spawned: 'transcription' with pid 10
whishper                | 2024-05-27 10:31:47,593 INFO success: backend entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
whishper                | 2024-05-27 10:31:47,593 INFO success: frontend entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
whishper                | 2024-05-27 10:31:47,593 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
whishper                | 2024-05-27 10:31:47,593 INFO success: transcription entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
whishper-postgres-1     | 2024-05-27 10:31:31.681 UTC [52] LOG:  database system was shut down at 2024-05-27 10:31:29 UTC
whishper-postgres-1     | 2024-05-27 10:31:31.688 UTC [49] LOG:  database system is ready to accept connections
whishper-postgres-1     |  done
whishper-postgres-1     | server started
whishper-postgres-1     | initdb: warning: enabling "trust" authentication for local connections
whishper-postgres-1     | initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
whishper-postgres-1     | CREATE DATABASE
whishper-postgres-1     | 
whishper-postgres-1     | 
whishper-postgres-1     | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
whishper-postgres-1     | 
whishper-postgres-1     | 2024-05-27 10:31:33.338 UTC [49] LOG:  received fast shutdown request
whishper-postgres-1     | waiting for server to shut down....2024-05-27 10:31:33.342 UTC [49] LOG:  aborting any active transactions
whishper-postgres-1     | 2024-05-27 10:31:33.343 UTC [49] LOG:  background worker "logical replication launcher" (PID 55) exited with exit code 1
whishper-postgres-1     | 2024-05-27 10:31:33.345 UTC [50] LOG:  shutting down
whishper-postgres-1     | 2024-05-27 10:31:33.349 UTC [50] LOG:  checkpoint starting: shutdown immediate
whishper-postgres-1     | 2024-05-27 10:31:34.296 UTC [50] LOG:  checkpoint complete: wrote 922 buffers (5.6%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.014 s, sync=0.914 s, total=0.951 s; sync files=301, longest=0.010 s, average=0.004 s; distance=4255 kB, estimate=4255 kB; lsn=0/1912048, redo lsn=0/1912048
whishper-postgres-1     | 2024-05-27 10:31:34.300 UTC [49] LOG:  database system is shut down
whishper-postgres-1     |  done
whishper-postgres-1     | server stopped
whishper-postgres-1     | 
whishper-postgres-1     | PostgreSQL init process complete; ready for start up.
whishper-postgres-1     | 
whishper-postgres-1     | 2024-05-27 10:31:34.407 UTC [1] LOG:  starting PostgreSQL 16.3 (Debian 16.3-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
whishper-postgres-1     | 2024-05-27 10:31:34.441 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
whishper-postgres-1     | 2024-05-27 10:31:34.442 UTC [1] LOG:  listening on IPv6 address "::", port 5432
whishper-postgres-1     | 2024-05-27 10:31:34.689 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
whishper-postgres-1     | 2024-05-27 10:31:34.703 UTC [65] LOG:  database system was shut down at 2024-05-27 10:31:34 UTC
whishper-postgres-1     | 2024-05-27 10:31:34.710 UTC [1] LOG:  database system is ready to accept connections
whishper-postgres-1     | 2024-05-27 10:36:34.802 UTC [63] LOG:  checkpoint starting: time
whishper-postgres-1     | 2024-05-27 10:36:34.942 UTC [63] LOG:  checkpoint complete: wrote 4 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.101 s, sync=0.017 s, total=0.140 s; sync files=3, longest=0.010 s, average=0.006 s; distance=0 kB, estimate=0 kB; lsn=0/1912130, redo lsn=0/19120F8
whishper-mongo-1        | 2024-05-27T10:31:28.812Z      INFO    ferretdb/main.go:280    Starting FerretDB v1.21.0...    {"version": "v1.21.0", "commit": "a3fb274d25bac13aea594ec34d603338bc00bfc3", "branch": "unknown", "dirty": true, "package": "docker", "debugBuild": false, "buildEnvironment": {"-buildmode":"exe","-compiler":"gc","CGO_ENABLED":"0","GOAMD64":"v1","GOARCH":"amd64","GOOS":"linux","go.version":"go1.22.1","vcs":"git","vcs.time":"2024-03-20T06:51:32Z"}, "uuid": "329088c5-0c80-4b22-aab5-282cce3031ea"}
whishper-mongo-1        | 2024-05-27T10:31:28.812Z      WARN    ferretdb/main.go:345    Failed to set GOMAXPROCS: open /sys/fs/cgroup/cpu/cpu.cfs_quota_us: no such file or directory.
whishper-mongo-1        | 2024-05-27T10:31:28.813Z      INFO    telemetry       telemetry/telemetry.go:122      Telemetry disabled.
whishper-mongo-1        | 2024-05-27T10:31:28.813Z      INFO    postgresql      handler/handler.go:144  Capped collections cleanup enabled.     {"interval": "1m0s"}
whishper-mongo-1        | 2024-05-27T10:31:28.813Z      INFO    listener        clientconn/listener.go:103      Listening on TCP [::]:27017 ...
whishper-mongo-1        | 2024-05-27T10:31:28.814Z      INFO    debug   debug/debug.go:103      Starting debug server on http://[::]:8080 ...
whishper-mongo-1        | 2024-05-27T10:31:28.814Z      INFO    debug   debug/debug.go:109      http://[::]:8080/debug/graphs - Visualize metrics
whishper-mongo-1        | 2024-05-27T10:31:28.814Z      INFO    debug   debug/debug.go:109      http://[::]:8080/debug/metrics - Metrics in Prometheus format
whishper-mongo-1        | 2024-05-27T10:31:28.814Z      INFO    debug   debug/debug.go:109      http://[::]:8080/debug/pprof - Runtime profiling data for pprof
whishper-mongo-1        | 2024-05-27T10:31:28.814Z      INFO    debug   debug/debug.go:109      http://[::]:8080/debug/vars - Expvar package metrics
whishper-mongo-1        | 2024-05-27T10:31:46.593Z      INFO    listener        clientconn/listener.go:303      Connection started      {"conn": "192.168.48.5:42302 -> 192.168.48.4:27017"}
whishper-mongo-1        | 2024-05-27T10:31:46.593Z      INFO    listener        clientconn/listener.go:303      Connection started      {"conn": "192.168.48.5:42304 -> 192.168.48.4:27017"}
whishper-mongo-1        | 2024-05-27T10:31:46.594Z      INFO    listener        clientconn/listener.go:303      Connection started      {"conn": "192.168.48.5:42306 -> 192.168.48.4:27017"}
whishper-mongo-1        | 2024-05-27T10:31:46.607Z      INFO    postgresql      tracelog/tracelog.go:335        Connect {"database": "whishper", "time": "9.289174ms", "pid": 70, "host": "postgres", "port": 5432}
whishper-mongo-1        | 2024-05-27T10:31:46.607Z      INFO    postgresql      tracelog/tracelog.go:335        Prepare {"sql": "SELECT version()", "time": "391.175µs", "alreadyPrepared": false, "pid": 70, "name": "stmtcache_df1f1d15d442789a5b9c81cdddf44d88d5748499cc488650"}
whishper-mongo-1        | 2024-05-27T10:31:46.608Z      INFO    postgresql      tracelog/tracelog.go:335        Query   {"sql": "SELECT version()", "args": [], "time": "618.817µs", "commandTag": "SELECT 1", "pid": 70}
whishper-mongo-1        | 2024-05-27T10:31:46.608Z      INFO    postgresql      tracelog/tracelog.go:335        Prepare {"name": "stmtcache_044acdca1c06eb0c67ff0d503eb085d2c5210a5f877152f3", "sql": "SHOW ALL", "time": "94.021µs", "alreadyPrepared": false, "pid": 70}
whishper-mongo-1        | 2024-05-27T10:31:46.609Z      INFO    postgresql      tracelog/tracelog.go:335        Query   {"commandTag": "SHOW", "pid": 70, "sql": "SHOW ALL", "args": [], "time": "901.81µs"}
whishper-mongo-1        | 2024-05-27T10:31:46.609Z      INFO    postgresql      pool/pool.go:131        Pool: connection succeed        {"username": "whishper"}
whishper-mongo-1        | 2024-05-27T10:31:46.609Z      INFO    postgresql      tracelog/tracelog.go:335        Prepare {"name": "stmtcache_24945b7c19db8098928de7adb02f361bb5b4c4d9ddd1197b", "sql": "SELECT schema_name\n\t\tFROM information_schema.schemata\n\t\tWHERE schema_name NOT LIKE 'pg_%'", "time": "659.217µs", "alreadyPrepared": false, "pid": 70}
whishper-mongo-1        | 2024-05-27T10:31:46.616Z      INFO    postgresql      tracelog/tracelog.go:335        Connect {"host": "postgres", "port": 5432, "database": "whishper", "time": "5.377231ms", "pid": 72}
whishper-mongo-1        | 2024-05-27T10:31:46.616Z      INFO    postgresql      tracelog/tracelog.go:335        Prepare {"time": "249.823µs", "alreadyPrepared": false, "pid": 72, "name": "stmtcache_df1f1d15d442789a5b9c81cdddf44d88d5748499cc488650", "sql": "SELECT version()"}
whishper-mongo-1        | 2024-05-27T10:31:46.616Z      INFO    postgresql      tracelog/tracelog.go:335        Query   {"pid": 72, "sql": "SELECT version()", "args": [], "time": "486.115µs", "commandTag": "SELECT 1"}
whishper-mongo-1        | 2024-05-27T10:31:46.619Z      INFO    postgresql      tracelog/tracelog.go:335        Prepare {"sql": "SELECT EXISTS (\n\t\t\t\tSELECT 1\n\t\t\t\tFROM information_schema.columns\n\t\t\t\tWHERE table_schema = $1 AND table_name = $2\n\t\t\t)", "time": "2.721431ms", "alreadyPrepared": false, "pid": 72, "name": "stmtcache_71cad5c48af040e3205c10487cf125c8a4e1749b43b8de71"}
whishper-mongo-1        | 2024-05-27T10:31:46.624Z      INFO    postgresql      tracelog/tracelog.go:335        Query   {"time": "7.211431ms", "commandTag": "SELECT 1", "pid": 72, "sql": "SELECT EXISTS (\n\t\t\t\tSELECT 1\n\t\t\t\tFROM information_schema.columns\n\t\t\t\tWHERE table_schema = $1 AND table_name = $2\n\t\t\t)", "args": ["public","_ferretdb_database_metadata"]}
whishper-mongo-1        | 2024-05-27T10:31:46.626Z      INFO    postgresql      tracelog/tracelog.go:335        Query   {"pid": 72, "sql": "SELECT EXISTS (\n\t\t\t\tSELECT 1\n\t\t\t\tFROM information_schema.columns\n\t\t\t\tWHERE table_schema = $1 AND table_name = $2\n\t\t\t)", "args": ["information_schema","_ferretdb_database_metadata"], "time": "2.449407ms", "commandTag": "SELECT 1"}
whishper-mongo-1        | 2024-05-27T10:31:46.626Z      INFO    postgresql      tracelog/tracelog.go:335        Query   {"pid": 70, "sql": "SELECT schema_name\n\t\tFROM information_schema.schemata\n\t\tWHERE schema_name NOT LIKE 'pg_%'", "args": [], "time": "17.690959ms", "commandTag": "SELECT 2"}
```

### Log files
```
[backend.err.log](https://github.com/pluja/whishper/files/15454787/backend.err.log)
[backend.out.log](https://github.com/pluja/whishper/files/15454788/backend.out.log)
[frontend.out.log](https://github.com/pluja/whishper/files/15454789/frontend.out.log)
[transcription.out.log](https://github.com/pluja/whishper/files/15454790/transcription.out.log)
[transcription.err.log](https://github.com/pluja/whishper/files/15454791/transcription.err.log)

```

### Docker Compose File

Override:
```
version: "3.9"

services:
  postgres:
    image: postgres
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER:-whishper}
      - POSTGRES_PASSWORD=${DB_PASS:-whishper}
      - POSTGRES_DB=whishper
    volumes:
      - ./whishper_data/db_data/ferret:/var/lib/postgresql/data

  mongo:
    image: ghcr.io/ferretdb/ferretdb
    restart: on-failure
    expose:
      - 27017
    env_file:
      - .env
    environment:
      - FERRETDB_POSTGRESQL_URL=postgres://${DB_USER:-whishper}:${DB_PASS:-whishper}@postgres:5432/whishper
    command: ["--telemetry=disable"]

  whishper:
    environment:
      FERRETDB_ENABLED: "true"
```

**compose:**
```
version: "3.9"

services:
  mongo:
    image: mongo
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./whishper_data/db_data:/data/db
      - ./whishper_data/db_data/logs/:/var/log/mongodb/
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER:-whishper}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS:-whishper}
    expose:
      - 27017
    command: ['--logpath', '/var/log/mongodb/mongod.log']

  translate:
    container_name: whisper-libretranslate
    image: libretranslate/libretranslate:latest
    restart: unless-stopped
    volumes:
      - ./whishper_data/libretranslate/data:/home/libretranslate/.local/share
      - ./whishper_data/libretranslate/cache:/home/libretranslate/.local/cache
    env_file:
      - .env
    tty: true
    environment:
      LT_DISABLE_WEB_UI: True
      LT_UPDATE_MODELS: True
    expose:
      - 5000
    networks:
      default:
        aliases:
          - translate
    healthcheck:
      test: ['CMD-SHELL', './venv/bin/python scripts/healthcheck.py']
      interval: 2s
      timeout: 3s
      retries: 5

  whishper:
    pull_policy: always
    image: pluja/whishper:${WHISHPER_VERSION:-latest}
    env_file:
      - .env
    volumes:
      - ./whishper_data/uploads:/app/uploads
      - ./whishper_data/logs:/var/log/whishper
    container_name: whishper
    restart: unless-stopped
    networks:
      default:
        aliases:
          - whishper
    ports:
      - 8082:80
    depends_on:
      - mongo
      - translate
    environment:
      PUBLIC_INTERNAL_API_HOST: "http://127.0.0.1:80"
      PUBLIC_TRANSLATION_API_HOST: ""
      PUBLIC_API_HOST: ${WHISHPER_HOST:-}
      PUBLIC_WHISHPER_PROFILE: cpu
      WHISPER_MODELS_DIR: /app/models
      UPLOAD_DIR: /app/uploads
      CPU_THREADS: 4
```

###  .env file:
```
# Libretranslate Configuration
## Check out https://github.com/LibreTranslate/LibreTranslate#configuration-parameters for more libretranslate configuration options
LT_LOAD_ONLY=es,en,fr

# Whisper Configuration
WHISPER_MODELS=tiny,small
WHISHPER_HOST=http://127.0.0.1:8082

# Database Configuration
DB_USER=whishper
DB_PASS=whishper
```
