### ISSUE TITLE
[BUG] How do I know it's still working on the transcription? "Waiting for transcription..." for several hours.

### ISSUE THREAD

**Issue by nothing2obvi** [pluja/whishper#128]
## **Description**
I am using `large-v3` to transcribe a 2.5-hour long FLAC file. It has said "Waiting for transcriiption..." for the past 13 hours.

### **To Reproduce**
1. Upload and transcribe file
2. It says "Waiting for transcription..."

### **Expected behavior**
There should be some kind of progress meter to indicate it is still working.

### Environment
- OS: OrbStack
- Browser: Opera
- Version: v3.1.4
- Hosting: Local via OrbStack (Docker)

### Docker Compose Logs

> Run the following command in the project folder, force the error, and paste the logs below: `docker compose logs -f --tail 50`

```
whisper-libretranslate  | Updating language models
whisper-libretranslate  | Found 92 models
whisper-libretranslate  | Keep 10 models
whisper-libretranslate  | Downloading English → French (1.9) ...
whisper-libretranslate  | Downloading English → Japanese (1.1) ...
whisper-libretranslate  | Downloading English → Korean (1.1) ...
whisper-libretranslate  | Downloading English → Spanish (1.0) ...
whisper-libretranslate  | Downloading English → Tagalog (1.9) ...
whisper-libretranslate  | Downloading French → English (1.9) ...
whisper-libretranslate  | Downloading Japanese → English (1.1) ...
whisper-libretranslate  | Downloading Korean → English (1.9) ...
whisper-libretranslate  | Downloading Spanish → English (1.9) ...
whisper-libretranslate  | Downloading Tagalog → English (1.9) ...
whisper-libretranslate  | Loaded support for 6 languages (10 models total)!
whisper-libretranslate  | Running on http://*:5000
whisper-libretranslate  | WARNING:waitress.queue:Task queue depth is 1
whisper-libretranslate  | WARNING:waitress.queue:Task queue depth is 2
whisper-libretranslate  | WARNING:waitress.queue:Task queue depth is 3
whisper-libretranslate  | WARNING:waitress.queue:Task queue depth is 4
whisper-libretranslate  | WARNING:waitress.queue:Task queue depth is 5
whisper-libretranslate  | WARNING:waitress.queue:Task queue depth is 6
whisper-libretranslate  | WARNING:waitress.queue:Task queue depth is 7
whishper                | 2024-12-31 05:40:22,749 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
whishper                | 2024-12-31 05:40:22,759 INFO supervisord started with pid 1
whishper                | 2024-12-31 05:40:23,783 INFO spawned: 'backend' with pid 6
whishper                | 2024-12-31 05:40:23,933 INFO spawned: 'frontend' with pid 7
whishper                | 2024-12-31 05:40:24,076 INFO spawned: 'nginx' with pid 8
whishper                | 2024-12-31 05:40:24,117 INFO spawned: 'transcription' with pid 9
whishper                | 2024-12-31 05:40:25,744 INFO success: backend entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
whishper                | 2024-12-31 05:40:25,744 INFO success: frontend entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
whishper                | 2024-12-31 05:40:25,744 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
whishper                | 2024-12-31 05:40:25,744 INFO success: transcription entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
whishper-mongo          | {"t":{"$date":"2024-12-31T05:40:39.048+00:00"},"s":"I",  "c":"CONTROL",  "id":4784906, "ctx":"SignalHandler","msg":"Shutting down the FlowControlTicketholder"}
whishper-mongo          | {"t":{"$date":"2024-12-31T05:40:39.048+00:00"},"s":"I",  "c":"-",        "id":20520,   "ctx":"SignalHandler","msg":"Stopping further Flow Control ticket acquisitions."}
whishper-mongo          | {"t":{"$date":"2024-12-31T05:40:39.048+00:00"},"s":"I",  "c":"CONTROL",  "id":4784908, "ctx":"SignalHandler","msg":"Shutting down the PeriodicThreadToAbortExpiredTransactions"}
whishper-mongo          | {"t":{"$date":"2024-12-31T05:40:39.049+00:00"},"s":"I",  "c":"REPL",     "id":4784909, "ctx":"SignalHandler","msg":"Shutting down the ReplicationCoordinator"}
whishper-mongo          | {"t":{"$date":"2024-12-31T05:40:39.049+00:00"},"s":"I",  "c":"SHARDING", "id":4784910, "ctx":"SignalHandler","msg":"Shutting down the ShardingInitializationMongoD"}
whishper-mongo          | {"t":{"$date":"2024-12-31T05:40:39.049+00:00"},"s":"I",  "c":"REPL",     "id":4784911, "ctx":"SignalHandler","msg":"Enqueuing the ReplicationStateTransitionLock for shutdown"}
whishper-mongo          | {"t":{"$date":"2024-12-31T05:40:39.049+00:00"},"s":"I",  "c":"-",        "id":4784912, "ctx":"SignalHandler","msg":"Killing all operations for shutdown"}
whishper-mongo          | {"t":{"$date":"2024-12-31T05:40:39.049+00:00"},"s":"I",  "c":"-",        "id":4695300, "ctx":"SignalHandler","msg":"Interrupted all currently running operations","attr":{"opsKilled":3}}
whishper-mongo          | {"t":{"$date":"2024-12-31T05:40:39.049+00:00"},"s":"I",  "c":"TENANT_M", "id":5093807, "ctx":"SignalHandler","msg":"Shutting down all TenantMigrationAccessBlockers on global shutdown"}
whishper-mongo          | {"t":{"$date":"2024-12-31T05:40:39.049+00:00"},"s":"I",  "c":"ASIO",     "id":22582,   "ctx":"TenantMigrationBlockerNet","msg":"Killing all outstanding egress activity."}
whishper-mongo          | {"t":{"$date":"2024-12-31T05:40:39.049+00:00"},"s":"I",  "c":"ASIO",     "id":6529201, "ctx":"SignalHandler","msg":"Network interface redundant shutdown","attr":{"state":"Stopped"}}
whishper-mongo          | {"t":{"$date":"2024-12-31T05:40:39.049+00:00"},"s":"I",  "c":"ASIO",     "id":22582,   "ctx":"SignalHandler","msg":"Killing all outstanding egress activity."}
whishper-mongo          | {"t":{"$date":"2024-12-31T05:40:39.049+00:00"},"s":"I",  "c":"COMMAND",  "id":4784913, "ctx":"SignalHandler","msg":"Shutting down all open transactions"}
whishper-mongo          | {"t":{"$date":"2024-12-31T05:40:39.049+00:00"},"s":"I",  "c":"REPL",     "id":4784914, "ctx":"SignalHandler","msg":"Acquiring the ReplicationStateTransitionLock for shutdown"}
whishper-mongo          | {"t":{"$date":"2024-12-31T05:40:39.049+00:00"},"s":"I",  "c":"INDEX",    "id":4784915, "ctx":"SignalHandler","msg":"Shutting down the IndexBuildsCoordinator"}
whishper-mongo          | {"t":{"$date":"2024-12-31T05:40:39.049+00:00"},"s":"I",  "c":"NETWORK",  "id":4784918, "ctx":"SignalHandler","msg":"Shutting down the ReplicaSetMonitor"}
whishper-mongo          | {"t":{"$date":"2024-12-31T05:40:39.049+00:00"},"s":"I",  "c":"SHARDING", "id":4784921, "ctx":"SignalHandler","msg":"Shutting down the MigrationUtilExecutor"}
whishper-mongo          | {"t":{"$date":"2024-12-31T05:40:39.049+00:00"},"s":"I",  "c":"ASIO",     "id":22582,   "ctx":"MigrationUtil-TaskExecutor","msg":"Killing all outstanding egress activity."}
whishper-mongo          | {"t":{"$date":"2024-12-31T05:40:39.049+00:00"},"s":"I",  "c":"NETWORK",  "id":20562,   "ctx":"SignalHandler","msg":"Shutdown: Closing open transport sessions"}
whishper-mongo          | {"t":{"$date":"2024-12-31T05:40:39.049+00:00"},"s":"I",  "c":"NETWORK",  "id":4784923, "ctx":"SignalHandler","msg":"Shutting down the ASIO transport SessionManager"}
whishper-mongo          | {"t":{"$date":"2024-12-31T05:40:39.049+00:00"},"s":"I",  "c":"CONTROL",  "id":4784927, "ctx":"SignalHandler","msg":"Shutting down the HealthLog"}
whishper-mongo          | {"t":{"$date":"2024-12-31T05:40:39.049+00:00"},"s":"I",  "c":"CONTROL",  "id":4784928, "ctx":"SignalHandler","msg":"Shutting down the TTL monitor"}
whishper-mongo          | {"t":{"$date":"2024-12-31T05:40:39.050+00:00"},"s":"I",  "c":"INDEX",    "id":3684100, "ctx":"SignalHandler","msg":"Shutting down TTL collection monitor thread"}
whishper-mongo          | {"t":{"$date":"2024-12-31T05:40:39.050+00:00"},"s":"I",  "c":"INDEX",    "id":3684101, "ctx":"SignalHandler","msg":"Finished shutting down TTL collection monitor thread"}
whishper-mongo          | {"t":{"$date":"2024-12-31T05:40:39.050+00:00"},"s":"I",  "c":"CONTROL",  "id":6278511, "ctx":"SignalHandler","msg":"Shutting down the Change Stream Expired Pre-images Remover"}
whishper-mongo          | {"t":{"$date":"2024-12-31T05:40:39.050+00:00"},"s":"I",  "c":"CONTROL",  "id":4784929, "ctx":"SignalHandler","msg":"Acquiring the global lock for shutdown"}
whishper-mongo          | {"t":{"$date":"2024-12-31T05:40:39.050+00:00"},"s":"I",  "c":"CONTROL",  "id":4784930, "ctx":"SignalHandler","msg":"Shutting down the storage engine"}
whishper-mongo          | {"t":{"$date":"2024-12-31T05:40:39.050+00:00"},"s":"I",  "c":"STORAGE",  "id":22320,   "ctx":"SignalHandler","msg":"Shutting down journal flusher thread"}
whishper-mongo          | {"t":{"$date":"2024-12-31T05:40:39.051+00:00"},"s":"I",  "c":"STORAGE",  "id":22321,   "ctx":"SignalHandler","msg":"Finished shutting down journal flusher thread"}
whishper-mongo          | {"t":{"$date":"2024-12-31T05:40:39.051+00:00"},"s":"I",  "c":"STORAGE",  "id":22322,   "ctx":"SignalHandler","msg":"Shutting down checkpoint thread"}
whishper-mongo          | {"t":{"$date":"2024-12-31T05:40:39.055+00:00"},"s":"I",  "c":"STORAGE",  "id":22323,   "ctx":"SignalHandler","msg":"Finished shutting down checkpoint thread"}
whishper-mongo          | {"t":{"$date":"2024-12-31T05:40:39.055+00:00"},"s":"I",  "c":"STORAGE",  "id":22261,   "ctx":"SignalHandler","msg":"Timestamp monitor shutting down"}
whishper-mongo          | {"t":{"$date":"2024-12-31T05:40:39.065+00:00"},"s":"I",  "c":"STORAGE",  "id":20282,   "ctx":"SignalHandler","msg":"Deregistering all the collections"}
whishper-mongo          | {"t":{"$date":"2024-12-31T05:40:39.065+00:00"},"s":"I",  "c":"STORAGE",  "id":22317,   "ctx":"SignalHandler","msg":"WiredTigerKVEngine shutting down"}
whishper-mongo          | {"t":{"$date":"2024-12-31T05:40:39.065+00:00"},"s":"I",  "c":"STORAGE",  "id":22318,   "ctx":"SignalHandler","msg":"Shutting down session sweeper thread"}
whishper-mongo          | {"t":{"$date":"2024-12-31T05:40:39.065+00:00"},"s":"I",  "c":"STORAGE",  "id":22319,   "ctx":"SignalHandler","msg":"Finished shutting down session sweeper thread"}
whishper-mongo          | {"t":{"$date":"2024-12-31T05:40:39.069+00:00"},"s":"I",  "c":"STORAGE",  "id":4795902, "ctx":"SignalHandler","msg":"Closing WiredTiger","attr":{"closeConfig":"leak_memory=true,use_timestamp=false,"}}
whishper-mongo          | {"t":{"$date":"2024-12-31T05:40:39.116+00:00"},"s":"I",  "c":"WTCHKPT",  "id":22430,   "ctx":"SignalHandler","msg":"WiredTiger message","attr":{"message":{"ts_sec":1735623639,"ts_usec":115982,"thread":"28:0x7f421aa576c0","session_name":"close_ckpt","category":"WT_VERB_CHECKPOINT_PROGRESS","category_id":7,"verbose_level":"DEBUG_1","verbose_level_id":1,"msg":"saving checkpoint snapshot min: 46, snapshot max: 46 snapshot count: 0, oldest timestamp: (0, 0) , meta checkpoint timestamp: (0, 0) base write gen: 1"}}}
whishper-mongo          | {"t":{"$date":"2024-12-31T05:40:39.921+00:00"},"s":"I",  "c":"WTRECOV",  "id":22430,   "ctx":"SignalHandler","msg":"WiredTiger message","attr":{"message":{"ts_sec":1735623639,"ts_usec":921323,"thread":"28:0x7f421aa576c0","session_name":"WT_CONNECTION.close","category":"WT_VERB_RECOVERY_PROGRESS","category_id":34,"verbose_level":"DEBUG_1","verbose_level_id":1,"msg":"shutdown checkpoint has successfully finished and ran for 820 milliseconds"}}}
whishper-mongo          | {"t":{"$date":"2024-12-31T05:40:39.921+00:00"},"s":"I",  "c":"WTRECOV",  "id":22430,   "ctx":"SignalHandler","msg":"WiredTiger message","attr":{"message":{"ts_sec":1735623639,"ts_usec":921490,"thread":"28:0x7f421aa576c0","session_name":"WT_CONNECTION.close","category":"WT_VERB_RECOVERY_PROGRESS","category_id":34,"verbose_level":"DEBUG_1","verbose_level_id":1,"msg":"shutdown was completed successfully and took 852ms, including 0ms for the rollback to stable, and 820ms for the checkpoint."}}}
whishper-mongo          | {"t":{"$date":"2024-12-31T05:40:40.261+00:00"},"s":"I",  "c":"STORAGE",  "id":4795901, "ctx":"SignalHandler","msg":"WiredTiger closed","attr":{"durationMillis":1192}}
whishper-mongo          | {"t":{"$date":"2024-12-31T05:40:40.261+00:00"},"s":"I",  "c":"STORAGE",  "id":22279,   "ctx":"SignalHandler","msg":"shutdown: removing fs lock..."}
whishper-mongo          | {"t":{"$date":"2024-12-31T05:40:40.261+00:00"},"s":"I",  "c":"-",        "id":4784931, "ctx":"SignalHandler","msg":"Dropping the scope cache for shutdown"}
whishper-mongo          | {"t":{"$date":"2024-12-31T05:40:40.261+00:00"},"s":"I",  "c":"FTDC",     "id":20626,   "ctx":"SignalHandler","msg":"Shutting down full-time diagnostic data capture"}
whishper-mongo          | {"t":{"$date":"2024-12-31T05:40:41.031+00:00"},"s":"I",  "c":"CONTROL",  "id":20565,   "ctx":"SignalHandler","msg":"Now exiting"}
whishper-mongo          | {"t":{"$date":"2024-12-31T05:40:41.055+00:00"},"s":"I",  "c":"CONTROL",  "id":8423404, "ctx":"SignalHandler","msg":"mongod shutdown complete","attr":{"Summary of time elapsed":{"Statistics":{"Enter terminal shutdown":"0 ms","Step down the replication coordinator for shutdown":"1 ms","Time spent in quiesce mode":"0 ms","Shut down FLE Crud subsystem":"1 ms","Shut down MirrorMaestro":"1 ms","Shut down WaitForMajorityService":"0 ms","Shut down the logical session cache":"11 ms","Shut down the global connection pool":"0 ms","Shut down the flow control ticket holder":"0 ms","Shut down the thread that aborts expired transactions":"0 ms","Kill all operations for shutdown":"0 ms","Shut down all tenant migration access blockers on global shutdown":"0 ms","Shut down all open transactions":"0 ms","Acquire the RSTL for shutdown":"0 ms","Shut down the IndexBuildsCoordinator and wait for index builds to finish":"0 ms","Shut down the replica set monitor":"0 ms","Shut down the migration util executor":"0 ms","Shut down the transport layer":"0 ms","Shut down the health log":"0 ms","Shut down the TTL monitor":"1 ms","Shut down expired pre-images and documents removers":"0 ms","Shut down the storage engine":"1211 ms","Wait for the oplog cap maintainer thread to stop":"0 ms","Shut down full-time data capture":"770 ms","Shut down online certificate status protocol manager":"0 ms","shutdownTask total elapsed time":"2009 ms"}}}}
whishper-mongo          | {"t":{"$date":"2024-12-31T05:40:41.055+00:00"},"s":"I",  "c":"CONTROL",  "id":23138,   "ctx":"SignalHandler","msg":"Shutting down","attr":{"exitCode":0}}
whishper-mongo          | 
whishper-mongo          | MongoDB init process complete; ready for start up.
whishper-mongo          | 

```

### Docker Compose File

```yaml
services:
  mongo:
    image: mongo
    container_name: whishper-mongo
    env_file:
      - /HDD/Docker/whishper/.env
    restart: unless-stopped
    volumes:
      - /HDD/Docker/whishper/db_data:/data/db
      - /HDD/Docker/whishper/db_data/logs/:/var/log/mongodb/
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER:-whishper}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS:-whishper}
    expose:
      - 27017
    command: ['--logpath', '/var/log/mongodb/mongod.log']

  translate:
    container_name: whisper-libretranslate
    image: libretranslate/libretranslate:latest
    restart: unless-stopped
    volumes:
      - /HDD/Docker/whishper/libretranslate/data:/home/libretranslate/.local/share
      - /HDD/Docker/whishper/libretranslate/cache:/home/libretranslate/.local/cache
    env_file:
      - /HDD/Docker/whishper/.env
    tty: true
    environment:
      LT_DISABLE_WEB_UI: True
      LT_UPDATE_MODELS: True
    expose:
      - 5000
    networks:
      default:
        aliases:
          - translate
    healthcheck:
      test: ['CMD-SHELL', './venv/bin/python scripts/healthcheck.py']
      interval: 2s
      timeout: 3s
      retries: 5

  whishper:
    pull_policy: always
    image: pluja/whishper:${WHISHPER_VERSION:-latest}
    env_file:
      - /HDD/Docker/whishper/.env
    volumes:
      - /HDD/Docker/whishper/uploads:/app/uploads
      - /HDD/Docker/whishper/logs:/var/log/whishper
    container_name: whishper
    restart: unless-stopped
    networks:
      default:
        aliases:
          - whishper
    ports:
      - 8082:80
    depends_on:
      - mongo
      - translate
    environment:
      PUBLIC_INTERNAL_API_HOST: "http://127.0.0.1:80"
      PUBLIC_TRANSLATION_API_HOST: ""
      PUBLIC_API_HOST: ${WHISHPER_HOST:-}
      PUBLIC_WHISHPER_PROFILE: cpu
      WHISPER_MODELS_DIR: /app/models
      UPLOAD_DIR: /app/uploads
      CPU_THREADS: 4
```

```env
# Libretranslate Configuration
## Check out https://github.com/LibreTranslate/LibreTranslate#configuration-parameters for more libretranslate configuration options
LT_LOAD_ONLY=es,en,fr,ko,ja,tl

# Whisper Configuration
WHISPER_MODELS=tiny,small,large-v3
WHISHPER_HOST=http://10.0.0.82:8082

# Database Configuration
DB_USER=username
DB_PASS=password
```
