### ISSUE TITLE
[BUG] Very slow and choppy CPU processing

### ISSUE THREAD

**Issue by kowalcj0** [pluja/whishper#152]
## **Description**
I'm running `Whishper` and `LibreTranslate` in a container inside Ubuntu 24.04.2 VM on a Proxmox server.
I've assigned two of my old 20 core (40 thread) Xeon CPUs 6148 to that VM and gave it 128GB RAM.
I don't have a dedicated GPU for LLM work (yet) thus I run them on CPUs only.
For some reason, the SST is super slow and runs in some kind of "bursts".
Processing of a 25 minutes aac file (extracted from old Japanese cartoon) takes half an hour or so.

I've tried different CPU governor settings in the Proxmox host. 
The `performance` setting gives me this kind of pattern:
![Image](https://github.com/user-attachments/assets/08a283d1-2b04-457b-98ff-5af49a7eb486)

and with `conservative` or `powersave` something even more stretched out:
![Image](https://github.com/user-attachments/assets/2d75fe06-a585-4082-b18e-57e91b47829e)

I've also tried different values of `CPU_THREADS`, 4, 8, 80 etc. 
But that made it even slower.

### **To Reproduce**
1. Go to 'home' page
2. Click on 'New Translation'
3. Select aac file and pick the model and language.
4. Observe CPU utilization

### **Expected behavior**
I expect that CPU should be pegged at 100% utilization while SST is happening. 

### Environment
- OS: Linux, Ubuntu 24.04.2 6.8.0-55-generic
- Browser: Firefox 
- Version: 135.0.1
- Hosting: VM in Proxmox behind Nginx Proxy Manager (Reverse Proxy)

### Docker Compose Logs

> Run the following command in the project folder, force the error, and paste the logs below: `docker compose logs -f --tail 50`

```
WARN[0000] /opt/stacks/ai-stack/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
whisper-libretranslate  | Updating language models
whisper-libretranslate  | Found 92 models
whisper-libretranslate  | Keep 10 models
whisper-libretranslate  | Downloading English → Japanese (1.1) ...
whisper-libretranslate  | Downloading English → Polish (1.9) ...
whisper-libretranslate  | Downloading English → Portuguese (1.0) ...
whisper-libretranslate  | Downloading English → Spanish (1.0) ...
whisper-libretranslate  | Downloading Japanese → English (1.1) ...
whisper-libretranslate  | Downloading Polish → English (1.9) ...
whisper-libretranslate  | Downloading Portuguese → English (1.0) ...
whisper-libretranslate  | Downloading Portuguese → Spanish (1.0) ...
whisper-libretranslate  | Downloading Spanish → English (1.9) ...
whisper-libretranslate  | Downloading Spanish → Portuguese (1.0) ...
whisper-libretranslate  | Loaded support for 5 languages (10 models total)!
whisper-libretranslate  | Running on http://*:5000
whisper-libretranslate  | Updating language models
whisper-libretranslate  | Found 92 models
whisper-libretranslate  | Keep 10 models
whisper-libretranslate  | Loaded support for 5 languages (10 models total)!
whisper-libretranslate  | Running on http://*:5000
whishper                | 2025-03-22 16:13:21,829 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
whishper                | 2025-03-22 16:13:21,834 INFO supervisord started with pid 1
whishper                | 2025-03-22 16:13:22,840 INFO spawned: 'backend' with pid 7
whishper                | 2025-03-22 16:13:22,848 INFO spawned: 'frontend' with pid 8
whishper                | 2025-03-22 16:13:22,854 INFO spawned: 'nginx' with pid 9
whishper                | 2025-03-22 16:13:22,867 INFO spawned: 'transcription' with pid 10
whishper                | 2025-03-22 16:13:24,608 INFO success: backend entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
whishper                | 2025-03-22 16:13:24,608 INFO success: frontend entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
whishper                | 2025-03-22 16:13:24,608 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
whishper                | 2025-03-22 16:13:24,608 INFO success: transcription entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
whishper                | 2025-03-22 16:28:43,761 WARN received SIGTERM indicating exit request
whishper                | 2025-03-22 16:28:43,764 INFO waiting for backend, frontend, nginx, transcription to die
whishper                | 2025-03-22 16:28:43,805 WARN stopped: transcription (terminated by SIGTERM)
whishper                | 2025-03-22 16:28:43,812 INFO stopped: nginx (exit status 0)
whishper                | 2025-03-22 16:28:43,822 WARN stopped: frontend (terminated by SIGTERM)
whishper                | 2025-03-22 16:28:43,847 WARN stopped: backend (terminated by SIGTERM)
whishper                | 2025-03-22 16:29:02,085 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
whishper                | 2025-03-22 16:29:02,090 INFO supervisord started with pid 1
whishper                | 2025-03-22 16:29:03,097 INFO spawned: 'backend' with pid 7
whishper                | 2025-03-22 16:29:03,105 INFO spawned: 'frontend' with pid 8
whishper                | 2025-03-22 16:29:03,113 INFO spawned: 'nginx' with pid 9
whishper                | 2025-03-22 16:29:03,120 INFO spawned: 'transcription' with pid 10
whishper                | 2025-03-22 16:29:04,836 INFO success: backend entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
whishper                | 2025-03-22 16:29:04,837 INFO success: frontend entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
whishper                | 2025-03-22 16:29:04,837 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
whishper                | 2025-03-22 16:29:04,837 INFO success: transcription entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
mongo-1                 | {"t":{"$date":"2025-03-22T16:13:27.673+00:00"},"s":"I",  "c":"-",        "id":20520,   "ctx":"SignalHandler","msg":"Stopping further Flow Control ticket acquisitions."}
mongo-1                 | {"t":{"$date":"2025-03-22T16:13:27.673+00:00"},"s":"I",  "c":"CONTROL",  "id":4784908, "ctx":"SignalHandler","msg":"Shutting down the PeriodicThreadToAbortExpiredTransactions"}
mongo-1                 | {"t":{"$date":"2025-03-22T16:13:27.674+00:00"},"s":"I",  "c":"REPL",     "id":4784909, "ctx":"SignalHandler","msg":"Shutting down the ReplicationCoordinator"}
mongo-1                 | {"t":{"$date":"2025-03-22T16:13:27.674+00:00"},"s":"I",  "c":"SHARDING", "id":4784910, "ctx":"SignalHandler","msg":"Shutting down the ShardingInitializationMongoD"}
mongo-1                 | {"t":{"$date":"2025-03-22T16:13:27.674+00:00"},"s":"I",  "c":"REPL",     "id":4784911, "ctx":"SignalHandler","msg":"Enqueuing the ReplicationStateTransitionLock for shutdown"}
mongo-1                 | {"t":{"$date":"2025-03-22T16:13:27.674+00:00"},"s":"I",  "c":"-",        "id":4784912, "ctx":"SignalHandler","msg":"Killing all operations for shutdown"}
mongo-1                 | {"t":{"$date":"2025-03-22T16:13:27.674+00:00"},"s":"I",  "c":"-",        "id":4695300, "ctx":"SignalHandler","msg":"Interrupted all currently running operations","attr":{"opsKilled":3}}
mongo-1                 | {"t":{"$date":"2025-03-22T16:13:27.674+00:00"},"s":"I",  "c":"TENANT_M", "id":5093807, "ctx":"SignalHandler","msg":"Shutting down all TenantMigrationAccessBlockers on global shutdown"}
mongo-1                 | {"t":{"$date":"2025-03-22T16:13:27.674+00:00"},"s":"I",  "c":"ASIO",     "id":22582,   "ctx":"TenantMigrationBlockerNet","msg":"Killing all outstanding egress activity."}
mongo-1                 | {"t":{"$date":"2025-03-22T16:13:27.674+00:00"},"s":"I",  "c":"ASIO",     "id":6529201, "ctx":"SignalHandler","msg":"Network interface redundant shutdown","attr":{"state":"Stopped"}}
mongo-1                 | {"t":{"$date":"2025-03-22T16:13:27.675+00:00"},"s":"I",  "c":"ASIO",     "id":22582,   "ctx":"SignalHandler","msg":"Killing all outstanding egress activity."}
mongo-1                 | {"t":{"$date":"2025-03-22T16:13:27.675+00:00"},"s":"I",  "c":"COMMAND",  "id":4784913, "ctx":"SignalHandler","msg":"Shutting down all open transactions"}
mongo-1                 | {"t":{"$date":"2025-03-22T16:13:27.675+00:00"},"s":"I",  "c":"REPL",     "id":4784914, "ctx":"SignalHandler","msg":"Acquiring the ReplicationStateTransitionLock for shutdown"}
mongo-1                 | {"t":{"$date":"2025-03-22T16:13:27.675+00:00"},"s":"I",  "c":"INDEX",    "id":4784915, "ctx":"SignalHandler","msg":"Shutting down the IndexBuildsCoordinator"}
mongo-1                 | {"t":{"$date":"2025-03-22T16:13:27.675+00:00"},"s":"I",  "c":"NETWORK",  "id":4784918, "ctx":"SignalHandler","msg":"Shutting down the ReplicaSetMonitor"}
mongo-1                 | {"t":{"$date":"2025-03-22T16:13:27.675+00:00"},"s":"I",  "c":"SHARDING", "id":4784921, "ctx":"SignalHandler","msg":"Shutting down the MigrationUtilExecutor"}
mongo-1                 | {"t":{"$date":"2025-03-22T16:13:27.676+00:00"},"s":"I",  "c":"ASIO",     "id":22582,   "ctx":"MigrationUtil-TaskExecutor","msg":"Killing all outstanding egress activity."}
mongo-1                 | {"t":{"$date":"2025-03-22T16:13:27.676+00:00"},"s":"I",  "c":"NETWORK",  "id":20562,   "ctx":"SignalHandler","msg":"Shutdown: Closing open transport sessions"}
mongo-1                 | {"t":{"$date":"2025-03-22T16:13:27.676+00:00"},"s":"I",  "c":"NETWORK",  "id":4784923, "ctx":"SignalHandler","msg":"Shutting down the ASIO transport SessionManager"}
mongo-1                 | {"t":{"$date":"2025-03-22T16:13:27.676+00:00"},"s":"I",  "c":"CONTROL",  "id":4784927, "ctx":"SignalHandler","msg":"Shutting down the HealthLog"}
mongo-1                 | {"t":{"$date":"2025-03-22T16:13:27.676+00:00"},"s":"I",  "c":"CONTROL",  "id":4784928, "ctx":"SignalHandler","msg":"Shutting down the TTL monitor"}
mongo-1                 | {"t":{"$date":"2025-03-22T16:13:27.676+00:00"},"s":"I",  "c":"INDEX",    "id":3684100, "ctx":"SignalHandler","msg":"Shutting down TTL collection monitor thread"}
mongo-1                 | {"t":{"$date":"2025-03-22T16:13:27.676+00:00"},"s":"I",  "c":"INDEX",    "id":3684101, "ctx":"SignalHandler","msg":"Finished shutting down TTL collection monitor thread"}
mongo-1                 | {"t":{"$date":"2025-03-22T16:13:27.677+00:00"},"s":"I",  "c":"CONTROL",  "id":6278511, "ctx":"SignalHandler","msg":"Shutting down the Change Stream Expired Pre-images Remover"}
mongo-1                 | {"t":{"$date":"2025-03-22T16:13:27.677+00:00"},"s":"I",  "c":"CONTROL",  "id":4784929, "ctx":"SignalHandler","msg":"Acquiring the global lock for shutdown"}
mongo-1                 | {"t":{"$date":"2025-03-22T16:13:27.677+00:00"},"s":"I",  "c":"CONTROL",  "id":4784930, "ctx":"SignalHandler","msg":"Shutting down the storage engine"}
mongo-1                 | {"t":{"$date":"2025-03-22T16:13:27.677+00:00"},"s":"I",  "c":"STORAGE",  "id":22320,   "ctx":"SignalHandler","msg":"Shutting down journal flusher thread"}
mongo-1                 | {"t":{"$date":"2025-03-22T16:13:27.677+00:00"},"s":"I",  "c":"STORAGE",  "id":22321,   "ctx":"SignalHandler","msg":"Finished shutting down journal flusher thread"}
mongo-1                 | {"t":{"$date":"2025-03-22T16:13:27.677+00:00"},"s":"I",  "c":"STORAGE",  "id":22322,   "ctx":"SignalHandler","msg":"Shutting down checkpoint thread"}
mongo-1                 | {"t":{"$date":"2025-03-22T16:13:27.677+00:00"},"s":"I",  "c":"STORAGE",  "id":22323,   "ctx":"SignalHandler","msg":"Finished shutting down checkpoint thread"}
mongo-1                 | {"t":{"$date":"2025-03-22T16:13:27.677+00:00"},"s":"I",  "c":"STORAGE",  "id":22261,   "ctx":"SignalHandler","msg":"Timestamp monitor shutting down"}
mongo-1                 | {"t":{"$date":"2025-03-22T16:13:27.678+00:00"},"s":"I",  "c":"STORAGE",  "id":20282,   "ctx":"SignalHandler","msg":"Deregistering all the collections"}
mongo-1                 | {"t":{"$date":"2025-03-22T16:13:27.678+00:00"},"s":"I",  "c":"STORAGE",  "id":22317,   "ctx":"SignalHandler","msg":"WiredTigerKVEngine shutting down"}
mongo-1                 | {"t":{"$date":"2025-03-22T16:13:27.678+00:00"},"s":"I",  "c":"STORAGE",  "id":22318,   "ctx":"SignalHandler","msg":"Shutting down session sweeper thread"}
mongo-1                 | {"t":{"$date":"2025-03-22T16:13:27.678+00:00"},"s":"I",  "c":"STORAGE",  "id":22319,   "ctx":"SignalHandler","msg":"Finished shutting down session sweeper thread"}
mongo-1                 | {"t":{"$date":"2025-03-22T16:13:27.688+00:00"},"s":"I",  "c":"STORAGE",  "id":4795902, "ctx":"SignalHandler","msg":"Closing WiredTiger","attr":{"closeConfig":"leak_memory=true,use_timestamp=false,"}}
mongo-1                 | {"t":{"$date":"2025-03-22T16:13:27.695+00:00"},"s":"I",  "c":"WTCHKPT",  "id":22430,   "ctx":"SignalHandler","msg":"WiredTiger message","attr":{"message":{"ts_sec":1742660007,"ts_usec":695854,"thread":"29:0x75779c2006c0","session_name":"close_ckpt","category":"WT_VERB_CHECKPOINT_PROGRESS","category_id":7,"verbose_level":"DEBUG_1","verbose_level_id":1,"msg":"saving checkpoint snapshot min: 46, snapshot max: 46 snapshot count: 0, oldest timestamp: (0, 0) , meta checkpoint timestamp: (0, 0) base write gen: 1"}}}
mongo-1                 | {"t":{"$date":"2025-03-22T16:13:27.740+00:00"},"s":"I",  "c":"WTRECOV",  "id":22430,   "ctx":"SignalHandler","msg":"WiredTiger message","attr":{"message":{"ts_sec":1742660007,"ts_usec":740051,"thread":"29:0x75779c2006c0","session_name":"WT_CONNECTION.close","category":"WT_VERB_RECOVERY_PROGRESS","category_id":34,"verbose_level":"DEBUG_1","verbose_level_id":1,"msg":"shutdown checkpoint has successfully finished and ran for 48 milliseconds"}}}
mongo-1                 | {"t":{"$date":"2025-03-22T16:13:27.740+00:00"},"s":"I",  "c":"WTRECOV",  "id":22430,   "ctx":"SignalHandler","msg":"WiredTiger message","attr":{"message":{"ts_sec":1742660007,"ts_usec":740708,"thread":"29:0x75779c2006c0","session_name":"WT_CONNECTION.close","category":"WT_VERB_RECOVERY_PROGRESS","category_id":34,"verbose_level":"DEBUG_1","verbose_level_id":1,"msg":"shutdown was completed successfully and took 52ms, including 0ms for the rollback to stable, and 48ms for the checkpoint."}}}
mongo-1                 | {"t":{"$date":"2025-03-22T16:13:27.763+00:00"},"s":"I",  "c":"STORAGE",  "id":4795901, "ctx":"SignalHandler","msg":"WiredTiger closed","attr":{"durationMillis":75}}
mongo-1                 | {"t":{"$date":"2025-03-22T16:13:27.763+00:00"},"s":"I",  "c":"STORAGE",  "id":22279,   "ctx":"SignalHandler","msg":"shutdown: removing fs lock..."}
mongo-1                 | {"t":{"$date":"2025-03-22T16:13:27.763+00:00"},"s":"I",  "c":"-",        "id":4784931, "ctx":"SignalHandler","msg":"Dropping the scope cache for shutdown"}
mongo-1                 | {"t":{"$date":"2025-03-22T16:13:27.763+00:00"},"s":"I",  "c":"FTDC",     "id":20626,   "ctx":"SignalHandler","msg":"Shutting down full-time diagnostic data capture"}
mongo-1                 | {"t":{"$date":"2025-03-22T16:13:27.774+00:00"},"s":"I",  "c":"CONTROL",  "id":20565,   "ctx":"SignalHandler","msg":"Now exiting"}
mongo-1                 | {"t":{"$date":"2025-03-22T16:13:27.775+00:00"},"s":"I",  "c":"CONTROL",  "id":8423404, "ctx":"SignalHandler","msg":"mongod shutdown complete","attr":{"Summary of time elapsed":{"Statistics":{"Enter terminal shutdown":"0 ms","Step down the replication coordinator for shutdown":"0 ms","Time spent in quiesce mode":"0 ms","Shut down FLE Crud subsystem":"1 ms","Shut down MirrorMaestro":"0 ms","Shut down WaitForMajorityService":"1 ms","Shut down the logical session cache":"0 ms","Shut down the global connection pool":"0 ms","Shut down the flow control ticket holder":"0 ms","Shut down the thread that aborts expired transactions":"0 ms","Kill all operations for shutdown":"0 ms","Shut down all tenant migration access blockers on global shutdown":"1 ms","Shut down all open transactions":"0 ms","Acquire the RSTL for shutdown":"0 ms","Shut down the IndexBuildsCoordinator and wait for index builds to finish":"0 ms","Shut down the replica set monitor":"0 ms","Shut down the migration util executor":"1 ms","Shut down the transport layer":"0 ms","Shut down the health log":"0 ms","Shut down the TTL monitor":"0 ms","Shut down expired pre-images and documents removers":"1 ms","Shut down the storage engine":"86 ms","Wait for the oplog cap maintainer thread to stop":"0 ms","Shut down full-time data capture":"10 ms","Shut down online certificate status protocol manager":"0 ms","shutdownTask total elapsed time":"105 ms"}}}}
mongo-1                 | {"t":{"$date":"2025-03-22T16:13:27.775+00:00"},"s":"I",  "c":"CONTROL",  "id":23138,   "ctx":"SignalHandler","msg":"Shutting down","attr":{"exitCode":0}}
mongo-1                 | 
mongo-1                 | MongoDB init process complete; ready for start up.
mongo-1                 | 
mongo-1                 | {"t":{"$date":"2025-03-22T16:29:01.318Z"},"s":"I",  "c":"CONTROL",  "id":20697,   "ctx":"main","msg":"Renamed existing log file","attr":{"oldLogPath":"/var/log/mongodb/mongod.log","newLogPath":"/var/log/mongodb/mongod.log.2025-03-22T16-29-01"}}

```

### Docker Compose File

I put `libretranslate` data in a separate folder as I was getting permissions issue (#669) and then I chowned it: `sudo chown -R 1032:1032 libretranslate_data/`

```yaml
version: "3.9"

services:
  mongo:
    image: mongo
    env_file:
      - .env
    restart: always
    volumes:
      - ./whishper_data/db_data:/data/db
      - ./whishper_data/db_data/logs/:/var/log/mongodb/
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER:-whishper}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS:-whishper}
    expose:
      - 27017
    command: ['--logpath', '/var/log/mongodb/mongod.log']

  translate:
    container_name: whisper-libretranslate
    image: libretranslate/libretranslate:latest
    restart: always
    volumes:
      - ./libretranslate_data:/home/libretranslate/.local:rw
    env_file:
      - .env
    tty: true
    environment:
      LT_DISABLE_WEB_UI: True
      LT_UPDATE_MODELS: True
    expose:
      - 5000
    networks:
      default:
        aliases:
          - translate
    healthcheck:
      test: ['CMD-SHELL', './venv/bin/python scripts/healthcheck.py']
      interval: 2s
      timeout: 3s
      retries: 5

  whishper:
    pull_policy: always
    image: pluja/whishper:${WHISHPER_VERSION:-latest}
    env_file:
      - .env
    volumes:
      - ./whishper_data/uploads:/app/uploads
      - ./whishper_data/logs:/var/log/whishper
    container_name: whishper
    restart: always
    networks:
      default:
        aliases:
          - whishper
    ports:
      - 8082:80
    depends_on:
      - mongo
      - translate
    environment:
      PUBLIC_INTERNAL_API_HOST: "http://127.0.0.1:80"
      PUBLIC_TRANSLATION_API_HOST: ""
      PUBLIC_API_HOST: ${WHISHPER_HOST:-}
      PUBLIC_WHISHPER_PROFILE: cpu
      WHISPER_MODELS_DIR: /app/models
      UPLOAD_DIR: /app/uploads
      CPU_THREADS: 80
```

and the `.env` file:
```
# Libretranslate Configuration
## Check out https://github.com/LibreTranslate/LibreTranslate#configuration-parameters for more libretranslate configuration options
LT_LOAD_ONLY=es,en,ja,pl,pt

# Whisper Configuration
WHISPER_MODELS=tiny,small,medium,large-v2,large-v3
WHISHPER_HOST=https://mydomain.duckdns.org

# Database Configuration
DB_USER=whishper
DB_PASS=whishper
```

**Comment by kowalcj0** [comment]
I did more testing today and it looks that any attempt to use `CPU_THREADS` > than the number of actual threads supported by physical CPU in one of the CPU sockets (in my case 40) results in either:
* Poor CPU utilization. Roughly between 15% and 25%
* using only 4 cores!

So, for now I'm going to stick with 1 CPU socket and 40 cores, use medium model and live with long-ish processing times.
This config yields the best results as CPU utilization is at 90-100% throughout SST process.
Here's an example CPU timeline:
![Image](https://github.com/user-attachments/assets/02706999-fbae-4a73-8613-e11b29031013)

Maybe someone will find the details from my testing useful to sort out their performance issues:

In all tests I used:
The same input file: a stereo AAC file of 26 minutes @ 48 kHz and CPU governor set to `performance`.

## VM in Proxmox had 1 CPU socket and 8 cores assigned. Total 40 VCPUs

### Test 1
WHISHPER_CPU_THREADS=8
LT_CPU_THREADS=4
Model: Medium Japanese
STT: ~ 21 minutes
Sub translation:
    * less than a minute for a translation to English
    * around minutes for a translation to Polish

### Test 2
WHISHPER_CPU_THREADS=8
LT_CPU_THREADS=4
Model: Medium Japanese
STT: ~17 minutes
Sub translation:
    * less than a minute for a translation to English
    * around minutes for a translation to Polish



## VM in Proxmox had 2 CPU sockets with 40 cores each. Total 80 VCPUs

### Test 3
WHISHPER_CPU_THREADS=80
LT_CPU_THREADS=4
Model: Medium Japanese
Problem: Whishper defaulted to 4 cores!
I've got the same v.slow & choppy processing.
I stopped the stack as SST would not finish in reasonable time.

### Test 4
WHISHPER_CPU_THREADS=40
LT_CPU_THREADS=4
Model: Medium Japanese
STT: ~9 minutes
Sub translation:
    * less than a minute for a translation to English
    * around minutes for a translation to Polish


## VM in Proxmox had 1 CPU socket with 80 cores. Total 80 VCPUs

### Test 5
WHISHPER_CPU_THREADS=40
LT_CPU_THREADS=40
Model: Medium Japanese
STT: ~8m30s
Sub translation:
    * ~45s for a translation to English
    * ~1m20s for a translation to Polish
    * Only 4 CPU cores were used

## Test 6
WHISHPER_CPU_THREADS=80
LT_CPU_THREADS=80
Model: Medium Japanese
Problem: Whishper defaulted to 4 cores!
I stopped the stack as SST would not finish in reasonable time.

### Test 7
WHISHPER_CPU_THREADS=50
LT_CPU_THREADS=8
Model: Medium Japanese
Problem: Whishper defaulted to 4 cores!
I stopped the stack as SST would not finish in reasonable time.


## VM in Proxmox had 1 CPU socket with 40 cores. Total 40 VCPUs

### Test 8
WHISHPER_CPU_THREADS=40
LT_CPU_THREADS=8
Model: Large-v3 Japanese
Problem: Poor CPU utilization. most of the time the cores we used between 15% and 25%
I haven't measured the time it took for STT to finish. Probably it was close to an hour or more. I went for dinner :)
Sub translation:
    * ~50s for a translation to English
    * ~1m15s for a translation to Polish
    * Only 4 CPU cores were used


I also made few small changes to `.env.` and `docker-compose.yml`:
* added CPU threads vars to `.env`
* mapped `/app/models` to local `./whishper_data/models`
* changed container names to shorter ones
* set `restart: always`

`.env`:
```
LT_LOAD_ONLY=es,en,ja,pl,pt
LT_CPU_THREADS=8

# Whisper Configuration
WHISPER_MODELS=tiny,small,medium,large-v2,large-v3
WHISHPER_HOST=https://mydomain.duckdns.org
WHISHPER_CPU_THREADS=40

# Database Configuration
DB_USER=whishper
DB_PASS=whishper
```

`docker-compose.yml`:
```yml
version: "3.9"

services:
  mongo:
    image: mongo
    container_name: mongo
    env_file:
      - .env
    restart: always
    volumes:
      - ./whishper_data/db_data:/data/db
      - ./whishper_data/db_data/logs/:/var/log/mongodb/
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER:-whishper}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS:-whishper}
    expose:
      - 27017
    command: ['--logpath', '/var/log/mongodb/mongod.log']

  translate:
    image: libretranslate/libretranslate:latest
    container_name: translate
    pull_policy: always
    restart: always
    env_file:
      - .env
    tty: true
    volumes:
      - ./whishper_data/libretranslate/data:/home/libretranslate/.local/share
      - ./whishper_data/libretranslate/cache:/home/libretranslate/.local/cache
    environment:
      LT_DISABLE_WEB_UI: True
      LT_UPDATE_MODELS: True
      THREADS: ${LT_CPU_THREADS-:4}
    expose:
      - 5000
    networks:
      default:
        aliases:
          - translate
    healthcheck:
      test: ['CMD-SHELL', './venv/bin/python scripts/healthcheck.py']
      interval: 2s
      timeout: 3s
      retries: 5

  whishper:
    pull_policy: always
    image: pluja/whishper:${WHISHPER_VERSION:-latest}
    container_name: whishper
    restart: always
    env_file:
      - .env
    volumes:
      - ./whishper_data/models:/app/models
      - ./whishper_data/uploads:/app/uploads
      - ./whishper_data/logs:/var/log/whishper
    networks:
      default:
        aliases:
          - whishper
    ports:
      - 8082:80
    depends_on:
      - mongo
      - translate
    environment:
      PUBLIC_INTERNAL_API_HOST: "http://127.0.0.1:80"
      PUBLIC_TRANSLATION_API_HOST: ""
      PUBLIC_API_HOST: ${WHISHPER_HOST:-}
      PUBLIC_WHISHPER_PROFILE: cpu
      WHISPER_MODELS_DIR: /app/models
      UPLOAD_DIR: /app/uploads
      CPU_THREADS: ${WHISHPER_CPU_THREADS:-4}
```
