### ISSUE TITLE
[BUG] websocket: close 1006 (abnormal closure): unexpected EOF / Invalid response status 500

### ISSUE THREAD

**Issue by grigio** [pluja/whishper#30]
I get this error

```
# .env
# Libretranslate Configuration
LT_LOAD_ONLY=en,it

# Whisper Configuration
WHISPER_MODELS=medium
WHISHPER_HOST=localhost:8082
DB_USER=whishper
DB_PASS=whishper
```

```

whisper-api          | INFO:     127.0.0.1:56020 - "GET /healthcheck/ HTTP/1.1" 200 OK
	whisper-api          | INFO:     127.0.0.1:44106 - "GET /healthcheck/ HTTP/1.1" 200 OK
nginx_1              | 192.168.1.77 - - [11/Oct/2023:08:29:52 +0000] "GET /ws/transcriptions HTTP/1.1" 101 552 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36"
whishper-backend     | 08:29:52 ERR api/server.go:58 > Error reading message error="websocket: close 1006 (abnormal closure): unexpected EOF"
whisper-api          | INFO:     172.26.0.6:37468 - "POST /transcribe?model_size=medium&task=transcribe&language=it&device=cpu HTTP/1.1" 307 Temporary Redirect
whisper-api          | Transcribing with model medium on device cpu...
whisper-api          | Downloading model medium...
whisper-api          | Model already cached...
whisper-api          | INFO:     172.26.0.6:37468 - "POST /transcribe/?model_size=medium&task=transcribe&language=it&device=cpu HTTP/1.1" 500 Internal Server Error
whishper-backend     | 08:29:53 DBG utils/utils.go:98 > Response from http://transcription-api:8000/transcribe?model_size=medium&task=transcribe&language=it&device=cpu: Internal Server Error
whishper-backend     | 08:29:53 DBG utils/utils.go:99 > Invalid response status 500:
whishper-backend     | 08:29:53 ERR monitor/monitor.go:78 > Error sending transcription request error="invalid status"
whishper-backend     | 08:29:53 ERR monitor/monitor.go:31 > Error transcribing error="invalid status"
whisper-api          | ERROR:    Exception in ASGI application
whisper-api          | Traceback (most recent call last):
whisper-api          |   File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
whisper-api          |     result = await app(  # type: ignore[func-returns-value]
whisper-api          |   File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
whisper-api          |     return await self.app(scope, receive, send)
whisper-api          |   File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 289, in __call__
whisper-api          |     await super().__call__(scope, receive, send)
whisper-api          |   File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
whisper-api          |     await self.middleware_stack(scope, receive, send)
whisper-api          |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
whisper-api          |     raise exc
whisper-api          |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
whisper-api          |     await self.app(scope, receive, _send)
whisper-api          |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
whisper-api          |     raise exc
whisper-api          |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
whisper-api          |     await self.app(scope, receive, sender)
whisper-api          |   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
whisper-api          |     raise e
whisper-api          |   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
whisper-api          |     await self.app(scope, receive, send)
whisper-api          |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
whisper-api          |     await route.handle(scope, receive, send)
whisper-api          |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
whisper-api          |     await self.app(scope, receive, send)
whisper-api          |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
whisper-api          |     response = await func(request)
whisper-api          |   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 273, in app
whisper-api          |     raw_response = await run_endpoint_function(
whisper-api          |   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 190, in run_endpoint_function
whisper-api          |     return await dependant.call(**values)
whisper-api          |   File "/app/main.py", line 23, in transcribe_endpoint
whisper-api          |     return await transcribe_file(file, model_size.value, language.value, device.value)
whisper-api          |   File "/app/transcribe.py", line 41, in transcribe_file
whisper-api          |     return await transcribe_audio(audio, model_size, language, device)
whisper-api          |   File "/app/transcribe.py", line 54, in transcribe_audio
whisper-api          |     model.load()
whisper-api          |   File "/app/backends/fasterwhisper.py", line 29, in load
whisper-api          |     self.model = WhisperModel(
whisper-api          |   File "/usr/local/lib/python3.10/site-packages/faster_whisper/transcribe.py", line 128, in __init__
whisper-api          |     self.model = ctranslate2.models.Whisper(
whisper-api          | RuntimeError: Unable to open file 'model.bin' in model '/app/models/faster-whisper-medium'
```

but it seems working downloading `model.bin` from https://huggingface.co/guillaumekln/faster-whisper-medium/tree/main and putting it manualli in the directory

**Comment by pluja** [comment]
Are you hosting it behind a reverse proxy? Or are you hosting it in localhost?

**Comment by grigio** [comment]
@pluja I'm using it via another computer in my LAN without reverse proxy

```
version: "3.9"

services:
  mongo:
    image: mongo
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./whishper_data/db_data:/data/db
      - ./whishper_data/db_data/logs/:/var/log/mongodb/
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER:-whishper}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS:-whishper}
    expose:
      - 27017
    command: ['--logpath', '/var/log/mongodb/mongod.log']
    healthcheck:
      test: mongosh --eval 'db.runCommand("ping").ok' --quiet
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 5s

  translate:
    container_name: whisper-libretranslate
    image: libretranslate/libretranslate:latest
    restart: unless-stopped
    volumes:
      - ./whishper_data/libretranslate/data:/home/libretranslate/.local/share
      - ./whishper_data/libretranslate/cache:/home/libretranslate/.local/cache
    env_file:
      - .env
    tty: true
    environment:
      - "LT_DISABLE_WEB_UI=true"
      #LT_UPDATE_MODELS: True
    expose:
      - 5000
    healthcheck:
      test: ['CMD-SHELL', './venv/bin/python scripts/healthcheck.py']
      interval: 15s
      timeout: 10s
      start_period: 5s
      retries: 5

  transcription-api:
    container_name: whisper-api
    image: pluja/whishper-transcription-api:latest
    env_file:
      - .env
    volumes:
      - ./whishper_data/whisper_models:/app/models
      - ./whishper_data/uploads:/app/uploads
    environment:
      - WHISPER_MODELS_DIR=/app/models
      - UPLOAD_DIR=/app/uploads
    restart: unless-stopped
    expose:
      - 8000

  whishper-backend:
    container_name: whishper-backend
    image: pluja/whishper-backend:latest
    env_file:
      - .env
    volumes:
      - ./whishper_data/uploads:/app/uploads
    restart: unless-stopped
    depends_on:
      mongo:
        condition: service_healthy
      translate:
        condition: service_healthy
      transcription-api:
        condition: service_healthy
    healthcheck:
      test: curl --fail http://localhost:8080/api/transcriptions || exit 1
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 5s
    expose:
      - 8080

  whishper-frontend:
    container_name: whishper-web
    image: pluja/whishper-frontend:latest
    env_file:
      - .env
    restart: unless-stopped
    environment:
      INTERNAL_API_HOST: "http://nginx:80"
      VITE_TRANSLATION_API_HOST: ""
      VITE_API_HOST: ${WHISHPER_HOST:-}
    depends_on:
      transcription-api:
        condition: service_healthy
    expose:
      - 3000

  nginx:
    image: nginx:1
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./whishper_data/uploads:/app/uploads
    depends_on:
      whishper-backend:
        condition: service_healthy
    ports:
      - 8082:80

```
