### ISSUE TITLE
[BUG] No respond from on the webui after adding video

### ISSUE THREAD

**Issue by ttforsd** [pluja/whishper#40]
**Describe the bug**
After choosing video and clicking starts, nothing seem to happen. Video doesn't show up on webui. No transcription seems to be happening. 
No errors in log 

**To Reproduce**
Fresh install of whispher using the latest get-whishper.sh

**Expected behavior**
video shows up on webui queue and start transcribing

**Screenshots**
<img width="965" alt="image" src="https://github.com/pluja/whishper/assets/29705247/1b3b5ce2-009e-4edc-ad28-8e04e4822b79">
Nothing happens after choosing a video and hitting start

**Device (please complete the following information):**
 - OS: Ubuntu 22.04.3 LTS
 - docker: Docker version 24.0.6, build ed223bc
 - Browser: edge and chrome 

**Additional context**
Whishper hosted on ubuntu server. Accessed from windows pc on local network.

**Comment by pluja** [comment]
Can you share any relevant log errrors (use `docker compose logs -f`, add some newlines and then force the error) and your docker-compose.yml file?

**Comment by ttforsd** [comment]
Sure thing! 
### **Docker compose logs**
```
whishper-web            | Listening on 0.0.0.0:3000
whisper-nginx-1         | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
whisper-nginx-1         | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
whisper-nginx-1         | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
whisper-nginx-1         | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
whisper-nginx-1         | 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
whisper-nginx-1         | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
whisper-nginx-1         | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
whisper-nginx-1         | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
whisper-nginx-1         | /docker-entrypoint.sh: Configuration complete; ready for start up
whisper-nginx-1         | 192.168.176.4 - - [30/Oct/2023:15:11:30 +0000] "GET /api/transcriptions HTTP/1.1" 200 4 "-" "undici"
whisper-nginx-1         | 192.168.0.94 - - [30/Oct/2023:15:11:30 +0000] "GET / HTTP/1.1" 200 2124 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36 Edg/118.0.2088.46"
whisper-nginx-1         | 192.168.0.94 - - [30/Oct/2023:15:11:30 +0000] "GET /logo.svg HTTP/1.1" 304 0 "http://192.168.0.244:8082/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36 Edg/118.0.2088.46"
whisper-nginx-1         | 192.168.0.94 - - [30/Oct/2023:15:11:31 +0000] "GET /favicon.webp HTTP/1.1" 304 0 "http://192.168.0.244:8082/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36 Edg/118.0.2088.46"
whisper-nginx-1         | 192.168.176.4 - - [30/Oct/2023:16:06:05 +0000] "GET /api/transcriptions HTTP/1.1" 200 4 "-" "undici"
whisper-nginx-1         | 192.168.0.94 - - [30/Oct/2023:16:06:05 +0000] "GET / HTTP/1.1" 200 2153 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36 Edg/118.0.2088.46"
whisper-nginx-1         | 192.168.176.4 - - [30/Oct/2023:16:44:59 +0000] "GET /api/transcriptions HTTP/1.1" 200 4 "-" "undici"
whisper-nginx-1         | 192.168.0.197 - - [30/Oct/2023:16:44:59 +0000] "GET / HTTP/1.1" 200 2131 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36 Edg/118.0.2088.69"
whisper-nginx-1         | 192.168.0.197 - - [30/Oct/2023:16:45:00 +0000] "GET /_app/immutable/assets/0.ece27e24.css HTTP/1.1" 200 70105 "http://192.168.0.244:8082/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36 Edg/118.0.2088.69"
whisper-nginx-1         | 192.168.0.197 - - [30/Oct/2023:16:45:00 +0000] "GET /_app/immutable/assets/Toaster.3a6d0da3.css HTTP/1.1" 200 4421 "http://192.168.0.244:8082/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36 Edg/118.0.2088.69"
whisper-nginx-1         | 192.168.0.197 - - [30/Oct/2023:16:45:00 +0000] "GET /_app/immutable/entry/start.416f8e94.js HTTP/1.1" 200 24888 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36 Edg/118.0.2088.69"
whisper-nginx-1         | 192.168.0.197 - - [30/Oct/2023:16:45:00 +0000] "GET /_app/immutable/chunks/scheduler.909669b5.js HTTP/1.1" 200 6874 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36 Edg/118.0.2088.69"
whisper-nginx-1         | 192.168.0.197 - - [30/Oct/2023:16:45:00 +0000] "GET /_app/immutable/chunks/singletons.18e46cb4.js HTTP/1.1" 200 2458 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36 Edg/118.0.2088.69"
whisper-nginx-1         | 192.168.0.197 - - [30/Oct/2023:16:45:00 +0000] "GET /_app/immutable/chunks/index.a5fb0175.js HTTP/1.1" 200 928 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36 Edg/118.0.2088.69"
whisper-nginx-1         | 192.168.0.197 - - [30/Oct/2023:16:45:00 +0000] "GET /_app/immutable/chunks/index.9130bb6b.js HTTP/1.1" 200 2306 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36 Edg/118.0.2088.69"
whisper-nginx-1         | 192.168.0.197 - - [30/Oct/2023:16:45:00 +0000] "GET /_app/immutable/entry/app.c911f74b.js HTTP/1.1" 200 6361 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36 Edg/118.0.2088.69"
whisper-nginx-1         | 192.168.0.197 - - [30/Oct/2023:16:45:00 +0000] "GET /_app/immutable/nodes/0.e42d6e11.js HTTP/1.1" 200 924 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36 Edg/118.0.2088.69"
whisper-nginx-1         | 192.168.0.197 - - [30/Oct/2023:16:45:00 +0000] "GET /_app/immutable/chunks/public.6cecea02.js HTTP/1.1" 200 245 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36 Edg/118.0.2088.69"
whisper-nginx-1         | 192.168.0.197 - - [30/Oct/2023:16:45:00 +0000] "GET /_app/immutable/nodes/2.a063f4a0.js HTTP/1.1" 200 41798 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36 Edg/118.0.2088.69"
whisper-nginx-1         | 192.168.0.197 - - [30/Oct/2023:16:45:00 +0000] "GET /_app/immutable/chunks/Toaster.f2e0788d.js HTTP/1.1" 200 21741 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36 Edg/118.0.2088.69"
whisper-nginx-1         | 192.168.0.197 - - [30/Oct/2023:16:45:00 +0000] "GET /logo.svg HTTP/1.1" 200 3128 "http://192.168.0.244:8082/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36 Edg/118.0.2088.69"
whisper-nginx-1         | 192.168.0.197 - - [30/Oct/2023:16:45:00 +0000] "GET /_app/immutable/nodes/1.ab8c6285.js HTTP/1.1" 200 1027 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36 Edg/118.0.2088.69"
whisper-mongo-1         | {"t":{"$date":"2023-10-30T15:08:33.033+00:00"},"s":"I",  "c":"SHARDING", "id":4784902, "ctx":"SignalHandler","msg":"Shutting down the WaitForMajorityService"}
whisper-mongo-1         | {"t":{"$date":"2023-10-30T15:08:33.055+00:00"},"s":"I",  "c":"CONTROL",  "id":4784903, "ctx":"SignalHandler","msg":"Shutting down the LogicalSessionCache"}
whisper-mongo-1         | {"t":{"$date":"2023-10-30T15:08:33.058+00:00"},"s":"I",  "c":"NETWORK",  "id":20562,   "ctx":"SignalHandler","msg":"Shutdown: going to close listening sockets"}
whisper-mongo-1         | {"t":{"$date":"2023-10-30T15:08:33.059+00:00"},"s":"I",  "c":"NETWORK",  "id":23017,   "ctx":"listener","msg":"removing socket file","attr":{"path":"/tmp/mongodb-27017.sock"}}
whisper-mongo-1         | {"t":{"$date":"2023-10-30T15:08:33.060+00:00"},"s":"I",  "c":"NETWORK",  "id":4784905, "ctx":"SignalHandler","msg":"Shutting down the global connection pool"}
whisper-mongo-1         | {"t":{"$date":"2023-10-30T15:08:33.060+00:00"},"s":"I",  "c":"CONTROL",  "id":4784906, "ctx":"SignalHandler","msg":"Shutting down the FlowControlTicketholder"}
whisper-mongo-1         | {"t":{"$date":"2023-10-30T15:08:33.060+00:00"},"s":"I",  "c":"-",        "id":20520,   "ctx":"SignalHandler","msg":"Stopping further Flow Control ticket acquisitions."}
whisper-mongo-1         | {"t":{"$date":"2023-10-30T15:08:33.060+00:00"},"s":"I",  "c":"CONTROL",  "id":4784908, "ctx":"SignalHandler","msg":"Shutting down the PeriodicThreadToAbortExpiredTransactions"}
whisper-mongo-1         | {"t":{"$date":"2023-10-30T15:08:33.060+00:00"},"s":"I",  "c":"REPL",     "id":4784909, "ctx":"SignalHandler","msg":"Shutting down the ReplicationCoordinator"}
whisper-mongo-1         | {"t":{"$date":"2023-10-30T15:08:33.060+00:00"},"s":"I",  "c":"SHARDING", "id":4784910, "ctx":"SignalHandler","msg":"Shutting down the ShardingInitializationMongoD"}
whisper-mongo-1         | {"t":{"$date":"2023-10-30T15:08:33.060+00:00"},"s":"I",  "c":"REPL",     "id":4784911, "ctx":"SignalHandler","msg":"Enqueuing the ReplicationStateTransitionLock for shutdown"}
whisper-mongo-1         | {"t":{"$date":"2023-10-30T15:08:33.060+00:00"},"s":"I",  "c":"-",        "id":4784912, "ctx":"SignalHandler","msg":"Killing all operations for shutdown"}
whisper-mongo-1         | {"t":{"$date":"2023-10-30T15:08:33.060+00:00"},"s":"I",  "c":"-",        "id":4695300, "ctx":"SignalHandler","msg":"Interrupted all currently running operations","attr":{"opsKilled":3}}
whisper-mongo-1         | {"t":{"$date":"2023-10-30T15:08:33.060+00:00"},"s":"I",  "c":"TENANT_M", "id":5093807, "ctx":"SignalHandler","msg":"Shutting down all TenantMigrationAccessBlockers on global shutdown"}
whisper-mongo-1         | {"t":{"$date":"2023-10-30T15:08:33.064+00:00"},"s":"I",  "c":"ASIO",     "id":22582,   "ctx":"TenantMigrationBlockerNet","msg":"Killing all outstanding egress activity."}
whisper-mongo-1         | {"t":{"$date":"2023-10-30T15:08:33.065+00:00"},"s":"I",  "c":"ASIO",     "id":6529201, "ctx":"SignalHandler","msg":"Network interface redundant shutdown","attr":{"state":"Stopped"}}
whisper-mongo-1         | {"t":{"$date":"2023-10-30T15:08:33.065+00:00"},"s":"I",  "c":"ASIO",     "id":22582,   "ctx":"SignalHandler","msg":"Killing all outstanding egress activity."}
whisper-mongo-1         | {"t":{"$date":"2023-10-30T15:08:33.065+00:00"},"s":"I",  "c":"COMMAND",  "id":4784913, "ctx":"SignalHandler","msg":"Shutting down all open transactions"}
whisper-mongo-1         | {"t":{"$date":"2023-10-30T15:08:33.065+00:00"},"s":"I",  "c":"REPL",     "id":4784914, "ctx":"SignalHandler","msg":"Acquiring the ReplicationStateTransitionLock for shutdown"}
whisper-mongo-1         | {"t":{"$date":"2023-10-30T15:08:33.065+00:00"},"s":"I",  "c":"INDEX",    "id":4784915, "ctx":"SignalHandler","msg":"Shutting down the IndexBuildsCoordinator"}
whisper-mongo-1         | {"t":{"$date":"2023-10-30T15:08:33.065+00:00"},"s":"I",  "c":"NETWORK",  "id":4784918, "ctx":"SignalHandler","msg":"Shutting down the ReplicaSetMonitor"}
whisper-mongo-1         | {"t":{"$date":"2023-10-30T15:08:33.065+00:00"},"s":"I",  "c":"SHARDING", "id":4784921, "ctx":"SignalHandler","msg":"Shutting down the MigrationUtilExecutor"}
whisper-mongo-1         | {"t":{"$date":"2023-10-30T15:08:33.065+00:00"},"s":"I",  "c":"ASIO",     "id":22582,   "ctx":"MigrationUtil-TaskExecutor","msg":"Killing all outstanding egress activity."}
whisper-mongo-1         | {"t":{"$date":"2023-10-30T15:08:33.066+00:00"},"s":"I",  "c":"COMMAND",  "id":4784923, "ctx":"SignalHandler","msg":"Shutting down the ServiceEntryPoint"}
whisper-mongo-1         | {"t":{"$date":"2023-10-30T15:08:33.066+00:00"},"s":"I",  "c":"CONTROL",  "id":4784927, "ctx":"SignalHandler","msg":"Shutting down the HealthLog"}
whisper-mongo-1         | {"t":{"$date":"2023-10-30T15:08:33.066+00:00"},"s":"I",  "c":"CONTROL",  "id":4784928, "ctx":"SignalHandler","msg":"Shutting down the TTL monitor"}
whisper-mongo-1         | {"t":{"$date":"2023-10-30T15:08:33.066+00:00"},"s":"I",  "c":"INDEX",    "id":3684100, "ctx":"SignalHandler","msg":"Shutting down TTL collection monitor thread"}
whisper-mongo-1         | {"t":{"$date":"2023-10-30T15:08:33.066+00:00"},"s":"I",  "c":"INDEX",    "id":3684101, "ctx":"SignalHandler","msg":"Finished shutting down TTL collection monitor thread"}
whisper-mongo-1         | {"t":{"$date":"2023-10-30T15:08:33.066+00:00"},"s":"I",  "c":"CONTROL",  "id":6278511, "ctx":"SignalHandler","msg":"Shutting down the Change Stream Expired Pre-images Remover"}
whisper-mongo-1         | {"t":{"$date":"2023-10-30T15:08:33.067+00:00"},"s":"I",  "c":"CONTROL",  "id":4784929, "ctx":"SignalHandler","msg":"Acquiring the global lock for shutdown"}
whisper-mongo-1         | {"t":{"$date":"2023-10-30T15:08:33.067+00:00"},"s":"I",  "c":"CONTROL",  "id":4784930, "ctx":"SignalHandler","msg":"Shutting down the storage engine"}
whisper-mongo-1         | {"t":{"$date":"2023-10-30T15:08:33.067+00:00"},"s":"I",  "c":"STORAGE",  "id":22320,   "ctx":"SignalHandler","msg":"Shutting down journal flusher thread"}
whisper-mongo-1         | {"t":{"$date":"2023-10-30T15:08:33.067+00:00"},"s":"I",  "c":"STORAGE",  "id":22321,   "ctx":"SignalHandler","msg":"Finished shutting down journal flusher thread"}
whisper-mongo-1         | {"t":{"$date":"2023-10-30T15:08:33.068+00:00"},"s":"I",  "c":"STORAGE",  "id":22322,   "ctx":"SignalHandler","msg":"Shutting down checkpoint thread"}
whisper-mongo-1         | {"t":{"$date":"2023-10-30T15:08:33.069+00:00"},"s":"I",  "c":"STORAGE",  "id":22323,   "ctx":"SignalHandler","msg":"Finished shutting down checkpoint thread"}
whisper-mongo-1         | {"t":{"$date":"2023-10-30T15:08:33.069+00:00"},"s":"I",  "c":"STORAGE",  "id":22261,   "ctx":"SignalHandler","msg":"Timestamp monitor shutting down"}
whisper-mongo-1         | {"t":{"$date":"2023-10-30T15:08:33.070+00:00"},"s":"I",  "c":"STORAGE",  "id":20282,   "ctx":"SignalHandler","msg":"Deregistering all the collections"}
whisper-mongo-1         | {"t":{"$date":"2023-10-30T15:08:33.070+00:00"},"s":"I",  "c":"STORAGE",  "id":22317,   "ctx":"SignalHandler","msg":"WiredTigerKVEngine shutting down"}
whisper-mongo-1         | {"t":{"$date":"2023-10-30T15:08:33.071+00:00"},"s":"I",  "c":"STORAGE",  "id":22318,   "ctx":"SignalHandler","msg":"Shutting down session sweeper thread"}
whisper-mongo-1         | {"t":{"$date":"2023-10-30T15:08:33.071+00:00"},"s":"I",  "c":"STORAGE",  "id":22319,   "ctx":"SignalHandler","msg":"Finished shutting down session sweeper thread"}
whisper-mongo-1         | {"t":{"$date":"2023-10-30T15:08:33.075+00:00"},"s":"I",  "c":"STORAGE",  "id":4795902, "ctx":"SignalHandler","msg":"Closing WiredTiger","attr":{"closeConfig":"leak_memory=true,use_timestamp=false,"}}
whisper-mongo-1         | {"t":{"$date":"2023-10-30T15:08:33.290+00:00"},"s":"I",  "c":"STORAGE",  "id":4795901, "ctx":"SignalHandler","msg":"WiredTiger closed","attr":{"durationMillis":215}}
whisper-mongo-1         | {"t":{"$date":"2023-10-30T15:08:33.290+00:00"},"s":"I",  "c":"STORAGE",  "id":22279,   "ctx":"SignalHandler","msg":"shutdown: removing fs lock..."}
whisper-mongo-1         | {"t":{"$date":"2023-10-30T15:08:33.290+00:00"},"s":"I",  "c":"-",        "id":4784931, "ctx":"SignalHandler","msg":"Dropping the scope cache for shutdown"}
whisper-mongo-1         | {"t":{"$date":"2023-10-30T15:08:33.290+00:00"},"s":"I",  "c":"FTDC",     "id":20626,   "ctx":"SignalHandler","msg":"Shutting down full-time diagnostic data capture"}
whisper-mongo-1         | {"t":{"$date":"2023-10-30T15:08:33.297+00:00"},"s":"I",  "c":"CONTROL",  "id":20565,   "ctx":"SignalHandler","msg":"Now exiting"}
whisper-mongo-1         | {"t":{"$date":"2023-10-30T15:08:33.297+00:00"},"s":"I",  "c":"CONTROL",  "id":23138,   "ctx":"SignalHandler","msg":"Shutting down","attr":{"exitCode":0}}
whisper-mongo-1         |
whisper-mongo-1         | MongoDB init process complete; ready for start up.
whisper-mongo-1         |
whishper-backend        |
whishper-backend        |  ┌───────────────────────────────────────────────────┐
whishper-backend        |  │                   Fiber v2.50.0                   │
whishper-backend        |  │               http://127.0.0.1:8080               │
whishper-backend        |  │       (bound on host 0.0.0.0 and port 8080)       │
whishper-backend        |  │                                                   │
whishper-backend        |  │ Handlers ............ 13  Processes ........... 1 │
whishper-backend        |  │ Prefork ....... Disabled  PID ................. 1 │
whishper-backend        |  └───────────────────────────────────────────────────┘
whishper-backend        |
whishper-backend        | 3:08PM INF Starting monitor!
whishper-backend        |
whishper-backend        |  ┌───────────────────────────────────────────────────┐
whishper-backend        |  │                   Fiber v2.50.0                   │
whishper-backend        | 4:12PM INF Starting monitor!
whishper-backend        |  │               http://127.0.0.1:8080               │
whishper-backend        |  │       (bound on host 0.0.0.0 and port 8080)       │
whishper-backend        |  │                                                   │
whishper-backend        |  │ Handlers ............ 13  Processes ........... 1 │
whishper-backend        |  │ Prefork ....... Disabled  PID ................. 1 │
whishper-backend        |  └───────────────────────────────────────────────────┘
whishper-backend        |
whisper-api             | INFO:     127.0.0.1:32904 - "GET /healthcheck/ HTTP/1.1" 200 OK
whisper-api             | INFO:     127.0.0.1:42848 - "GET /healthcheck/ HTTP/1.1" 200 OK
whisper-api             | INFO:     127.0.0.1:57068 - "GET /healthcheck/ HTTP/1.1" 200 OK
whisper-api             | INFO:     127.0.0.1:48222 - "GET /healthcheck/ HTTP/1.1" 200 OK
whisper-api             | INFO:     127.0.0.1:38700 - "GET /healthcheck/ HTTP/1.1" 200 OK
whisper-api             | INFO:     127.0.0.1:34376 - "GET /healthcheck/ HTTP/1.1" 200 OK
whisper-api             | INFO:     127.0.0.1:39664 - "GET /healthcheck/ HTTP/1.1" 200 OK
whisper-libretranslate  | Updating language models
whisper-libretranslate  | Found 86 models
whisper-libretranslate  | Keep 6 models
whisper-libretranslate  | Downloading Chinese → English (1.9) ...
whisper-libretranslate  | Downloading English → Chinese (1.9) ...
whisper-libretranslate  | Downloading English → French (1.0) ...
whisper-libretranslate  | Downloading English → Spanish (1.0) ...
whisper-libretranslate  | Downloading French → English (1.0) ...
whisper-libretranslate  | Downloading Spanish → English (1.0) ...
whisper-libretranslate  | Loaded support for 4 languages (6 models total)!
whisper-libretranslate  | Running on http://0.0.0.0:5000
whisper-api             | INFO:     127.0.0.1:46654 - "GET /healthcheck/ HTTP/1.1" 200 OK
whisper-api             | INFO:     127.0.0.1:55892 - "GET /healthcheck/ HTTP/1.1" 200 OK
whisper-api             | INFO:     127.0.0.1:54450 - "GET /healthcheck/ HTTP/1.1" 200 OK
whisper-api             | INFO:     127.0.0.1:60392 - "GET /healthcheck/ HTTP/1.1" 200 OK
whisper-api             | INFO:     127.0.0.1:56616 - "GET /healthcheck/ HTTP/1.1" 200 OK
whisper-api             | INFO:     127.0.0.1:53338 - "GET /healthcheck/ HTTP/1.1" 200 OK
whisper-api             | INFO:     127.0.0.1:39592 - "GET /healthcheck/ HTTP/1.1" 200 OK
whisper-api             | INFO:     127.0.0.1:42896 - "GET /healthcheck/ HTTP/1.1" 200 OK
whisper-api             | INFO:     127.0.0.1:41374 - "GET /healthcheck/ HTTP/1.1" 200 OK
whisper-api             | INFO:     127.0.0.1:49230 - "GET /healthcheck/ HTTP/1.1" 200 OK
whisper-api             | INFO:     127.0.0.1:39350 - "GET /healthcheck/ HTTP/1.1" 200 OK
whisper-api             | INFO:     127.0.0.1:39546 - "GET /healthcheck/ HTTP/1.1" 200 OK
whisper-api             | INFO:     127.0.0.1:42754 - "GET /healthcheck/ HTTP/1.1" 200 OK
whisper-api             | INFO:     127.0.0.1:32834 - "GET /healthcheck/ HTTP/1.1" 200 OK
whisper-api             | INFO:     127.0.0.1:56464 - "GET /healthcheck/ HTTP/1.1" 200 OK
whisper-api             | INFO:     127.0.0.1:60400 - "GET /healthcheck/ HTTP/1.1" 200 OK
whisper-api             | INFO:     127.0.0.1:59468 - "GET /healthcheck/ HTTP/1.1" 200 OK
whisper-api             | INFO:     127.0.0.1:44292 - "GET /healthcheck/ HTTP/1.1" 200 OK
whisper-api             | INFO:     127.0.0.1:59556 - "GET /healthcheck/ HTTP/1.1" 200 OK
whisper-api             | INFO:     127.0.0.1:44608 - "GET /healthcheck/ HTTP/1.1" 200 OK
whisper-api             | INFO:     127.0.0.1:33748 - "GET /healthcheck/ HTTP/1.1" 200 OK
whisper-api             | INFO:     127.0.0.1:41824 - "GET /healthcheck/ HTTP/1.1" 200 OK
whisper-api             | INFO:     127.0.0.1:49928 - "GET /healthcheck/ HTTP/1.1" 200 OK
whisper-api             | INFO:     127.0.0.1:52800 - "GET /healthcheck/ HTTP/1.1" 200 OK
whisper-api             | INFO:     127.0.0.1:35714 - "GET /healthcheck/ HTTP/1.1" 200 OK
whisper-api             | INFO:     127.0.0.1:57142 - "GET /healthcheck/ HTTP/1.1" 200 OK
whisper-api             | INFO:     127.0.0.1:39694 - "GET /healthcheck/ HTTP/1.1" 200 OK
whisper-api             | INFO:     127.0.0.1:38460 - "GET /healthcheck/ HTTP/1.1" 200 OK
whisper-api             | INFO:     127.0.0.1:34110 - "GET /healthcheck/ HTTP/1.1" 200 OK
whisper-api             | INFO:     127.0.0.1:46210 - "GET /healthcheck/ HTTP/1.1" 200 OK
whisper-api             | INFO:     127.0.0.1:41786 - "GET /healthcheck/ HTTP/1.1" 200 OK
whisper-api             | INFO:     127.0.0.1:38562 - "GET /healthcheck/ HTTP/1.1" 200 OK
whisper-api             | INFO:     127.0.0.1:49162 - "GET /healthcheck/ HTTP/1.1" 200 OK
whisper-api             | INFO:     127.0.0.1:38326 - "GET /healthcheck/ HTTP/1.1" 200 OK
whisper-api             | INFO:     127.0.0.1:47284 - "GET /healthcheck/ HTTP/1.1" 200 OK
whisper-api             | INFO:     127.0.0.1:42640 - "GET /healthcheck/ HTTP/1.1" 200 OK
whisper-api             | INFO:     127.0.0.1:59088 - "GET /healthcheck/ HTTP/1.1" 200 OK
whisper-api             | INFO:     127.0.0.1:57976 - "GET /healthcheck/ HTTP/1.1" 200 OK
whisper-api             | INFO:     127.0.0.1:40510 - "GET /healthcheck/ HTTP/1.1" 200 OK
whisper-api             | INFO:     127.0.0.1:40686 - "GET /healthcheck/ HTTP/1.1" 200 OK
whisper-api             | INFO:     127.0.0.1:45000 - "GET /healthcheck/ HTTP/1.1" 200 OK
whisper-api             | INFO:     127.0.0.1:55436 - "GET /healthcheck/ HTTP/1.1" 200 OK
whisper-api             | INFO:     127.0.0.1:40804 - "GET /healthcheck/ HTTP/1.1" 200 OK



whisper-nginx-1         | 192.168.176.4 - - [30/Oct/2023:16:45:13 +0000] "GET /api/transcriptions HTTP/1.1" 200 4 "-" "undici"
whisper-nginx-1         | 192.168.0.197 - - [30/Oct/2023:16:45:13 +0000] "GET / HTTP/1.1" 200 2125 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36 Edg/118.0.2088.69"
whisper-nginx-1         | 192.168.0.197 - - [30/Oct/2023:16:45:13 +0000] "GET /favicon.webp HTTP/1.1" 200 4074 "http://192.168.0.244:8082/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36 Edg/118.0.2088.69"
whisper-api             | INFO:     127.0.0.1:53956 - "GET /healthcheck/ HTTP/1.1" 200 OK
```
I reloaded the webpage and added a video after the new lines. Nothing seems to happen. whishper_data/uploads is empty.

### My docker-compose.yml file
```
version: "3.9"

services:
  mongo:
    image: mongo
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./whishper_data/db_data:/data/db
      - ./whishper_data/db_data/logs/:/var/log/mongodb/
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER:-whishper}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS:-whishper}
    expose:
      - 27017
    command: ['--logpath', '/var/log/mongodb/mongod.log']
    healthcheck:
      test: mongosh --eval 'db.runCommand("ping").ok' --quiet
      interval: 2s
      timeout: 3s
      retries: 5

  translate-cpu:
    container_name: whisper-libretranslate
    profiles: ["cpu"]
    image: libretranslate/libretranslate:latest
    restart: unless-stopped
    volumes:
      - ./whishper_data/libretranslate/data:/home/libretranslate/.local/share
      - ./whishper_data/libretranslate/cache:/home/libretranslate/.local/cache
    env_file:
      - .env
    tty: true
    environment:
      LT_DISABLE_WEB_UI: True
      #LT_UPDATE_MODELS: True
    expose:
      - 5000
    networks:
      default:
        aliases:
          - translate
    healthcheck:
      test: ['CMD-SHELL', './venv/bin/python scripts/healthcheck.py']
      interval: 2s
      timeout: 3s
      retries: 5

  translate-gpu:
    container_name: whisper-libretranslate
    image: libretranslate/libretranslate:latest-cuda
    profiles: ["gpu"]
    restart: unless-stopped
    volumes:
      - ./whishper_data/libretranslate/data:/home/libretranslate/.local/share
      - ./whishper_data/libretranslate/cache:/home/libretranslate/.local/cache
    env_file:
      - .env
    user: root
    tty: true
    environment:
      LT_DISABLE_WEB_UI: True
      LT_LOAD_ONLY: ${LT_LOAD_ONLY:-en,fr,es}
      #LT_UPDATE_MODELS: True
    expose:
      - 5000
    networks:
      default:
        aliases:
          - translate
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
    healthcheck:
      test: ['CMD-SHELL', './venv/bin/python scripts/healthcheck.py']
      interval: 2s
      timeout: 3s
      retries: 5

  transcription-api-cpu:
    container_name: whisper-api
    profiles: ["cpu"]
    image: pluja/whishper-transcription-api:latest
    env_file:
      - .env
    volumes:
      - ./whishper_data/whisper_models:/app/models
      - ./whishper_data/uploads:/app/uploads
    environment:
      - WHISPER_MODELS_DIR=/app/models
      - UPLOAD_DIR=/app/uploads
    networks:
      default:
        aliases:
          - transcription-api
    restart: unless-stopped
    expose:
      - 8000

  transcription-api-gpu:
    container_name: whisper-api
    profiles: ["gpu"]
    image: pluja/whishper-transcription-api:latest-gpu
    env_file:
      - .env
    volumes:
      - ./whishper_data/whisper_models:/app/models
      - ./whishper_data/uploads:/app/uploads
    environment:
      WHISPER_MODELS_DIR: /app/models
      UPLOAD_DIR: /app/uploads
    restart: unless-stopped
    expose:
      - 8000
    networks:
      default:
        aliases:
          - transcription-api
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]

  whishper-backend:
    container_name: whishper-backend
    image: pluja/whishper-backend:latest
    env_file:
      - .env
    volumes:
      - ./whishper_data/uploads:/app/uploads
    restart: unless-stopped
    depends_on:
      mongo:
        condition: service_healthy
    healthcheck:
      test: curl --fail http://localhost:8080/api/transcriptions || exit 1
      interval: 2s
      timeout: 2s
      retries: 5
    expose:
      - 8080

  whishper-frontend:
    container_name: whishper-web
    image: pluja/whishper-frontend:latest
    env_file:
      - .env
    restart: unless-stopped
    environment:
      PUBLIC_INTERNAL_API_HOST: "http://nginx:80"
      PUBLIC_TRANSLATION_API_HOST: ""
      PUBLIC_API_HOST: ${WHISHPER_HOST:-}
      PUBLIC_WHISHPER_PROFILE: ${COMPOSE_PROFILES:-false}
    expose:
      - 3000

  nginx:
    image: nginx:1
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./whishper_data/uploads:/app/uploads
    depends_on:
      whishper-backend:
        condition: service_healthy
    ports:
      - 8082:80

```
### My .env file
```
# PROFILE
COMPOSE_PROFILES=cpu # set to 'gpu' if you have GPU with cuda support, read https://whishper.net/guides/gpu

# Libretranslate Configuration
LT_LOAD_ONLY=es,en,fr,zh

# Whisper Configuration
WHISPER_MODELS=tiny,small,medium
WHISHPER_HOST=http://127.0.0.1:8082

# Database Configuration
DB_USER=whishper
DB_PASS=whishper
```
