### ISSUE TITLE
[BUG] ERR_SSL_WRONG_VERSION_NUMBER

### ISSUE THREAD

**Issue by grigio** [pluja/whishper#42]
## **Description**
It halts somewhere during translation

### **To Reproduce**
1. upload video file
2. crash error 500 - id-65400c146cd3244731584fa8 Failed: Could not transcribe.

### **Expected behavior**
See the transcription

### Environment
- OS: Linux
- Browser: Chrome
- Version: 119
- Hosting: Docker

### Docker Compose Logs

> Run the following command in the project folder, force the error, and paste the logs below: `docker compose logs -f --tail 50`

With the latest update it seems some API requires HTTPS SSL

```
ux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36"
nginx_1              | 192.168.32.1 - - [30/Oct/2023:17:54:49 +0000] "GET /undefined/languages HTTP/1.1" 404 706 "http://mia.lan:8082/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36"
whishper-web         | Listening on 0.0.0.0:3000
whishper-web         | TypeError: fetch failed
whishper-web         |     at fetch (file:///app/shims.js:20346:13)
whishper-web         |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
whishper-web         |     at async resolve (file:///app/server/index.js:3661:14)
whishper-web         |     at async respond (file:///app/server/index.js:3479:22)
whishper-web         |     at async fetch (file:///app/server/index.js:3289:26)
whishper-web         |     at async Object.fetch (file:///app/server/index.js:3229:12)
whishper-web         |     at async file:///app/server/index.js:1341:20
whishper-web         |     at async load (file:///app/server/chunks/0-3c61a3ef.js:8:20)
whishper-web         |     at async load_data (file:///app/server/index.js:1323:18)
whishper-web         |     at async file:///app/server/index.js:2660:18 {
whishper-web         |   cause: [Error: B8894C42D67F0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:354:
whishper-web         |   ] {
whishper-web         |     library: 'SSL routines',
whishper-web         |     reason: 'wrong version number',
whishper-web         |     code: 'ERR_SSL_WRONG_VERSION_NUMBER'
whishper-web         |   }
whishper-web         | }
whishper-web         | TypeError: fetch failed
whishper-web         |     at fetch (file:///app/shims.js:20346:13)
whishper-web         |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
whishper-web         |     at async resolve (file:///app/server/index.js:3636:16)
whishper-web         |     at async respond (file:///app/server/index.js:3479:22)
whishper-web         |     at async fetch (file:///app/server/index.js:3289:26)
whishper-web         |     at async Object.fetch (file:///app/server/index.js:3229:12)
whishper-web         |     at async file:///app/server/index.js:1341:20
whishper-web         |     at async load (file:///app/server/chunks/0-3c61a3ef.js:8:20)
whishper-web         |     at async load_data (file:///app/server/index.js:1323:18)
whishper-web         |     at async respond_with_error (file:///app/server/index.js:2291:20) {
whishper-web         |   cause: [Error: B8894C42D67F0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:354:
whishper-web         |   ] {
whishper-web         |     library: 'SSL routines',
whishper-web         |     reason: 'wrong version number',
whishper-web         |     code: 'ERR_SSL_WRONG_VERSION_NUMBER'
whishper-web         |   }
whishper-web         | }
whisper-api          |   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 289, in __call__
whisper-api          |     await super().__call__(scope, receive, send)
whisper-api          |   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
whisper-api          |     await self.middleware_stack(scope, receive, send)
whisper-api          |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
whisper-api          |     raise exc
whisper-api          |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
whisper-api          |     await self.app(scope, receive, _send)
whisper-api          |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
whisper-api          |     raise exc
whisper-api          |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
whisper-api          |     await self.app(scope, receive, sender)
whisper-api          |   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
whisper-api          |     raise e
whisper-api          |   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
whisper-api          |     await self.app(scope, receive, send)
whisper-api          |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
whisper-api          |     await route.handle(scope, receive, send)
whisper-api          |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
whisper-api          |     await self.app(scope, receive, send)
whisper-api          |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
whisper-api          |     response = await func(request)
whisper-api          |                ^^^^^^^^^^^^^^^^^^^
whisper-api          |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 273, in app
whisper-api          |     raw_response = await run_endpoint_function(
whisper-api          |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
whisper-api          |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 190, in run_endpoint_function
whisper-api          |     return await dependant.call(**values)
whisper-api          |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
whisper-api          |   File "/app/main.py", line 26, in transcribe_endpoint
whisper-api          |     return await transcribe_file(file, model_size.value, language.value, device)
whisper-api          |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
whisper-api          |   File "/app/transcribe.py", line 41, in transcribe_file
whisper-api          |     return await transcribe_audio(audio, model_size, language, device)
whisper-api          |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
whisper-api          |   File "/app/transcribe.py", line 54, in transcribe_audio
whisper-api          |     model.load()
whisper-api          |   File "/app/backends/fasterwhisper.py", line 29, in load
whisper-api          |     self.model = WhisperModel(
whisper-api          |                  ^^^^^^^^^^^^^
whisper-api          |   File "/usr/local/lib/python3.11/site-packages/faster_whisper/transcribe.py", line 128, in __init__
whisper-api          |     self.model = ctranslate2.models.Whisper(
whisper-api          |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
whisper-api          | RuntimeError: Unable to open file 'model.bin' in model '/app/models/faster-whisper-medium'
whisper-api          | INFO:     127.0.0.1:43256 - "GET /healthcheck/ HTTP/1.1" 200 OK
whisper-api          | INFO:     127.0.0.1:37584 - "GET /healthcheck/ HTTP/1.1" 200 OK
whisper-api          | INFO:     127.0.0.1:53780 - "GET /healthcheck/ HTTP/1.1" 200 OK
whisper-api          | INFO:     127.0.0.1:41508 - "GET /healthcheck/ HTTP/1.1" 200 OK
whisper-api          | INFO:     127.0.0.1:40696 - "GET /healthcheck/ HTTP/1.1" 200 OK
whisper-api          | INFO:     127.0.0.1:39932 - "GET /healthcheck/ HTTP/1.1" 200 OK
nginx_1              | 192.168.1.77 - - [30/Oct/2023:20:03:59 +0000] "GET /undefined/languages HTTP/1.1" 404 706 "http://mia.lan:8082/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36"
nginx_1              | 192.168.1.77 - - [30/Oct/2023:20:04:04 +0000] "GET /undefined/languages HTTP/1.1" 404 706 "http://mia.lan:8082/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36"
nginx_1              | 192.168.1.77 - - [30/Oct/2023:20:04:09 +0000] "GET /undefined/languages HTTP/1.1" 404 706 "http://mia.lan:8082/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36"
nginx_1              | 192.168.1.77 - - [30/Oct/2023:20:04:14 +0000] "GET /undefined/languages HTTP/1.1" 404 706 "http://mia.lan:8082/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36"
nginx_1              | 192.168.1.77 - - [30/Oct/2023:20:04:19 +0000] "GET /undefined/languages HTTP/1.1" 404 706 "http://mia.lan:8082/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36"
nginx_1              | 192.168.1.77 - - [30/Oct/2023:20:04:24 +0000] "GET /undefined/languages HTTP/1.1" 404 706 "http://mia.lan:8082/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36"
nginx_1              | 192.168.1.77 - - [30/Oct/2023:20:04:29 +0000] "GET /undefined/languages HTTP/1.1" 404 706 "http://mia.lan:8082/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36"
nginx_1              | 192.168.1.77 - - [30/Oct/2023:20:04:32 +0000] "GET /ws/transcriptions HTTP/1.1" 101 835 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36"
nginx_1              | 192.168.1.77 - - [30/Oct/2023:20:04:34 +0000] "GET /undefined/languages HTTP/1.1" 404 706 "http://mia.lan:8082/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36"
nginx_1              | 192.168.1.77 - - [30/Oct/2023:20:04:39 +0000] "GET /undefined/languages HTTP/1.1" 404 706 "http://mia.lan:8082/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36"
nginx_1              | 192.168.1.77 - - [30/Oct/2023:20:04:57 +0000] "GET /undefined/languages HTTP/1.1" 404 706 "http://mia.lan:8082/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36"
nginx_1              | 192.168.1.77 - - [30/Oct/2023:20:05:34 +0000] "GET /ws/transcriptions HTTP/1.1" 101 0 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36"
nginx_1              | 192.168.1.77 - - [30/Oct/2023:20:05:57 +0000] "GET /undefined/languages HTTP/1.1" 404 706 "http://mia.lan:8082/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36"
nginx_1              | 192.168.1.77 - - [30/Oct/2023:20:06:36 +0000] "GET /ws/transcriptions HTTP/1.1" 101 0 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36"
nginx_1              | 192.168.1.77 - - [30/Oct/2023:20:06:57 +0000] "GET /undefined/languages HTTP/1.1" 404 706 "http://mia.lan:8082/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36"
whishper-backend     | 
whishper-backend     |  ┌───────────────────────────────────────────────────┐ 
whishper-backend     |  │                   Fiber v2.50.0                   │ 
whishper-backend     |  │               http://127.0.0.1:8080               │ 
whishper-backend     |  │       (bound on host 0.0.0.0 and port 8080)       │ 
whishper-backend     |  │                                                   │ 
whishper-backend     |  │ Handlers ............ 13  Processes ........... 1 │ 
whishper-backend     |  │ Prefork ....... Disabled  PID ................. 1 │ 
whishper-backend     |  └───────────────────────────────────────────────────┘ 
whishper-backend     | 
whishper-backend     | 7:37PM INF Starting monitor!
whishper-backend     | 7:38PM ERR Error reading message error="websocket: close 1006 (abnormal closure): unexpected EOF"
whishper-backend     | 7:39PM ERR Error reading message error="websocket: close 1006 (abnormal closure): unexpected EOF"
whishper-backend     | 7:40PM ERR Error reading message error="websocket: close 1006 (abnormal closure): unexpected EOF"
whishper-backend     | 7:41PM ERR Error reading message error="websocket: close 1006 (abnormal closure): unexpected EOF"
whishper-backend     | 7:42PM ERR Error reading message error="websocket: close 1006 (abnormal closure): unexpected EOF"
whishper-backend     | 7:43PM ERR Error reading message error="websocket: close 1006 (abnormal closure): unexpected EOF"
whishper-backend     | 7:44PM ERR Error reading message error="websocket: close 1006 (abnormal closure): unexpected EOF"
whishper-backend     | 7:45PM ERR Error reading message error="websocket: close 1006 (abnormal closure): unexpected EOF"
whishper-backend     | 7:46PM ERR Error reading message error="websocket: close 1006 (abnormal closure): unexpected EOF"
whishper-backend     | 7:48PM ERR Error reading message error="websocket: close 1006 (abnormal closure): unexpected EOF"
whishper-backend     | 7:49PM ERR Error reading message error="websocket: close 1006 (abnormal closure): unexpected EOF"
whishper-backend     | 7:50PM ERR Error reading message error="websocket: close 1006 (abnormal closure): unexpected EOF"
whishper-backend     | 7:50PM ERR Error sending transcription request error="invalid status"
whishper-backend     | 7:50PM ERR Error transcribing error="invalid status"
whishper-backend     | 7:51PM ERR Error sending transcription request error="invalid status"
whishper-backend     | 7:51PM ERR Error transcribing error="invalid status"
whishper-backend     | 7:52PM ERR Error reading message error="websocket: close 1006 (abnormal closure): unexpected EOF"
whishper-backend     | 7:53PM ERR Error reading message error="websocket: close 1006 (abnormal closure): unexpected EOF"
whishper-backend     | 7:54PM ERR Error reading message error="websocket: close 1006 (abnormal closure): unexpected EOF"
whishper-backend     | 7:55PM ERR Error reading message error="websocket: close 1006 (abnormal closure): unexpected EOF"
whishper-backend     | 7:56PM ERR Error reading message error="websocket: close 1006 (abnormal closure): unexpected EOF"
whishper-backend     | 7:57PM ERR Error reading message error="websocket: close 1006 (abnormal closure): unexpected EOF"
whishper-backend     | 7:58PM ERR Error reading message error="websocket: close 1006 (abnormal closure): unexpected EOF"
whishper-backend     | 7:59PM ERR Error reading message error="websocket: close 1006 (abnormal closure): unexpected EOF"
whishper-backend     | 8:00PM ERR Error reading message error="websocket: close 1006 (abnormal closure): unexpected EOF"
whishper-backend     | 8:01PM ERR Error reading message error="websocket: close 1006 (abnormal closure): unexpected EOF"
whishper-backend     | 8:02PM ERR Error reading message error="websocket: close 1006 (abnormal closure): unexpected EOF"
whishper-backend     | 8:03PM ERR Error sending transcription request error="invalid status"
whishper-backend     | 8:03PM ERR Error transcribing error="invalid status"
whishper-backend     | 8:04PM ERR Error reading message error="websocket: close 1006 (abnormal closure): unexpected EOF"
whishper-backend     | 8:05PM ERR Error reading message error="websocket: close 1006 (abnormal closure): unexpected EOF"
whishper-backend     | 8:06PM ERR Error reading message error="websocket: close 1006 (abnormal closure): unexpected EOF"
whisper-libretranslate | Running on http://0.0.0.0:5000
whisper-api          | INFO:     127.0.0.1:53582 - "GET /healthcheck/ HTTP/1.1" 200 OK
whisper-api          | INFO:     127.0.0.1:45828 - "GET /healthcheck/ HTTP/1.1" 200 OK
nginx_1              | 192.168.1.77 - - [30/Oct/2023:20:07:38 +0000] "GET /ws/transcriptions HTTP/1.1" 101 0 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36"
whishper-backend     | 8:07PM ERR Error reading message error="websocket: close 1006 (abnormal closure): unexpected EOF"

```

### Docker Compose File

```yaml
version: "3.9"

services:
  mongo:
    image: mongo
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./whishper_data/db_data:/data/db
      - ./whishper_data/db_data/logs/:/var/log/mongodb/
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER:-whishper}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS:-whishper}
    expose:
      - 27017
    command: ['--logpath', '/var/log/mongodb/mongod.log']
    healthcheck:
      test: mongosh --eval 'db.runCommand("ping").ok' --quiet
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 5s

  translate:
    container_name: whisper-libretranslate
    image: libretranslate/libretranslate:v1.4.0
    restart: unless-stopped
    volumes:
      - ./whishper_data/libretranslate/data:/home/libretranslate/.local/share
      - ./whishper_data/libretranslate/cache:/home/libretranslate/.local/cache
    env_file:
      - .env
    tty: true
    environment:
      - "LT_DISABLE_WEB_UI=true"
      #LT_UPDATE_MODELS: True
    expose:
      - 5000
    healthcheck:
      test: ['CMD-SHELL', './venv/bin/python scripts/healthcheck.py']
      interval: 15s
      timeout: 10s
      start_period: 5s
      retries: 5

  transcription-api:
    container_name: whisper-api
    image: pluja/whishper-transcription-api:latest
    env_file:
      - .env
    volumes:
      - ./whishper_data/whisper_models:/app/models
      - ./whishper_data/uploads:/app/uploads
    environment:
      - WHISPER_MODELS_DIR=/app/models
      - UPLOAD_DIR=/app/uploads
    restart: unless-stopped
    expose:
      - 8000

  whishper-backend:
    container_name: whishper-backend
    image: pluja/whishper-backend:latest
    env_file:
      - .env
    volumes:
      - ./whishper_data/uploads:/app/uploads
    restart: unless-stopped
    depends_on:
      mongo:
        condition: service_healthy
      translate:
        condition: service_healthy
      transcription-api:
        condition: service_healthy
    healthcheck:
      test: curl --fail http://localhost:8080/api/transcriptions || exit 1
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 5s
    expose:
      - 8080

  whishper-frontend:
    container_name: whishper-web
    image: pluja/whishper-frontend:latest
    env_file:
      - .env
    restart: unless-stopped
    environment:
      INTERNAL_API_HOST: "http://nginx:80"
      VITE_TRANSLATION_API_HOST: ""
      VITE_API_HOST: ${WHISHPER_HOST:-}
    depends_on:
      transcription-api:
        condition: service_healthy
    expose:
      - 3000

  nginx:
    image: nginx:1
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./whishper_data/uploads:/app/uploads
    depends_on:
      whishper-backend:
        condition: service_healthy
    ports:
      - 8082:80
```
