### ISSUE TITLE
libretranslate: loading additional languages doesn't work

### ISSUE THREAD

**Issue by thob** [pluja/whishper#46]
I can't translate, the pull down menu doesn't offer anything. 

### **To Reproduce**
After transcription I want to translate but the pulldown menu doesn't offer anything. 
I first started with the default .env settings but then edited to add `it` and `de` like `LT_LOAD_ONLY=es,en,fr,it,de` however it didn't even download the respective packages

I'm on Linux Mint 21.2 on i5-5250U CPU @ 1.60GHz × 2

## Logs and Configuration
I get this in the log
whishper-backend        | 5:39PM ERR Error reading message error="websocket: close 1006 (abnormal closure): unexpected EOF"

### Docker Compose Logs

```
whisper-libretranslate  | Running on http://0.0.0.0:5000
whisper-libretranslate  | Running on http://0.0.0.0:5000
whishper-web            | Listening on 0.0.0.0:3000
whishper-web            | Listening on 0.0.0.0:3000
whishper-web            | Listening on 0.0.0.0:3000
whishper-web            | Listening on 0.0.0.0:3000
whisper-libretranslate  | Running on http://0.0.0.0:5000
whisper-libretranslate  | Running on http://0.0.0.0:5000
whishper-backend        | 5:13PM ERR Error reading message error="websocket: close 1006 (abnormal closure): unexpected EOF"
whishper-backend        | 5:14PM ERR Error reading message error="websocket: close 1006 (abnormal closure): unexpected EOF"
whishper-backend        | 5:14PM ERR Error reading message error="websocket: close 1006 (abnormal closure): unexpected EOF"
whishper-backend        | 5:15PM ERR Error reading message error="websocket: close 1006 (abnormal closure): unexpected EOF"
whishper-backend        | 5:15PM ERR Error reading message error="websocket: close 1006 (abnormal closure): unexpected EOF"
thomas-mongo-1          | {"t":{"$date":"2023-11-04T16:28:38.651Z"},"s":"I",  "c":"CONTROL",  "id":20697,   "ctx":"main","msg":"Renamed existing log file","attr":{"oldLogPath":"/var/log/mongodb/mongod.log","newLogPath":"/var/log/mongodb/mongod.log.2023-11-04T16-28-38"}}
thomas-mongo-1          | {"t":{"$date":"2023-11-04T16:42:50.442Z"},"s":"I",  "c":"CONTROL",  "id":20697,   "ctx":"main","msg":"Renamed existing log file","attr":{"oldLogPath":"/var/log/mongodb/mongod.log","newLogPath":"/var/log/mongodb/mongod.log.2023-11-04T16-42-50"}}
thomas-mongo-1          | {"t":{"$date":"2023-11-04T17:22:00.208Z"},"s":"I",  "c":"CONTROL",  "id":20697,   "ctx":"main","msg":"Renamed existing log file","attr":{"oldLogPath":"/var/log/mongodb/mongod.log","newLogPath":"/var/log/mongodb/mongod.log.2023-11-04T17-22-00"}}
thomas-mongo-1          | {"t":{"$date":"2023-11-04T17:25:07.239Z"},"s":"I",  "c":"CONTROL",  "id":20697,   "ctx":"main","msg":"Renamed existing log file","attr":{"oldLogPath":"/var/log/mongodb/mongod.log","newLogPath":"/var/log/mongodb/mongod.log.2023-11-04T17-25-07"}}
whishper-backend        | 5:16PM ERR Error reading message error="websocket: close 1006 (abnormal closure): unexpected EOF"
whishper-backend        | 5:16PM ERR Error reading message error="websocket: close 1006 (abnormal closure): unexpected EOF"
whishper-backend        | 5:17PM ERR Error reading message error="websocket: close 1006 (abnormal closure): unexpected EOF"
whishper-backend        | 5:17PM ERR Error reading message error="websocket: close 1006 (abnormal closure): unexpected EOF"
whishper-backend        | 5:18PM ERR Error reading message error="websocket: close 1006 (abnormal closure): unexpected EOF"
whishper-backend        | 5:18PM ERR Error reading message error="websocket: close 1006 (abnormal closure): unexpected EOF"
whishper-backend        | 5:19PM ERR Error reading message error="websocket: close 1006 (abnormal closure): unexpected EOF"
whishper-backend        | 5:19PM ERR Error reading message error="websocket: close 1006 (abnormal closure): unexpected EOF"
whishper-backend        | 5:20PM ERR Error reading message error="websocket: close 1006 (abnormal closure): unexpected EOF"
whishper-backend        | 5:20PM ERR Error reading message error="websocket: close 1006 (abnormal closure): unexpected EOF"
whishper-backend        | 5:22PM INF Starting monitor!
whishper-backend        | 
whishper-backend        | 
whishper-backend        |  ┌───────────────────────────────────────────────────┐ 
whishper-backend        |  │                   Fiber v2.50.0                   │ 
whishper-backend        |  │               http://127.0.0.1:8080               │ 
whishper-backend        |  │       (bound on host 0.0.0.0 and port 8080)       │ 
whishper-backend        |  │                                                   │ 
whishper-backend        |  │ Handlers ............ 13  Processes ........... 1 │ 
whishper-backend        |  │ Prefork ....... Disabled  PID ................. 1 │ 
whishper-backend        |  └───────────────────────────────────────────────────┘ 
whishper-backend        | 
whishper-backend        | 
whishper-backend        | 
whishper-backend        | 
whishper-backend        |  ┌───────────────────────────────────────────────────┐ 
whishper-backend        |  │                   Fiber v2.50.0                   │ 
whishper-backend        |  │               http://127.0.0.1:8080               │ 
whishper-backend        |  │       (bound on host 0.0.0.0 and port 8080)       │ 
whishper-backend        |  │                                                   │ 
whishper-backend        |  │ Handlers ............ 13  Processes ........... 1 │ 
whishper-backend        |  │ Prefork ....... Disabled  PID ................. 1 │ 
whishper-backend        |  └───────────────────────────────────────────────────┘ 
whishper-backend        | 
whishper-backend        | 
whishper-backend        | 5:25PM INF Starting monitor!
whishper-backend        | 5:26PM ERR Error reading message error="websocket: close 1006 (abnormal closure): unexpected EOF"
whishper-backend        | 5:27PM ERR Error reading message error="websocket: close 1006 (abnormal closure): unexpected EOF"
whishper-backend        | 5:28PM ERR Error reading message error="websocket: close 1006 (abnormal closure): unexpected EOF"
whishper-backend        | 5:29PM ERR Error reading message error="websocket: close 1006 (abnormal closure): unexpected EOF"
whishper-backend        | 5:30PM ERR Error reading message error="websocket: close 1006 (abnormal closure): unexpected EOF"
whishper-backend        | 5:31PM ERR Error reading message error="websocket: close 1006 (abnormal closure): unexpected EOF"
whishper-backend        | 5:32PM ERR Error reading message error="websocket: close 1006 (abnormal closure): unexpected EOF"
whishper-backend        | 5:33PM ERR Error reading message error="websocket: close 1006 (abnormal closure): unexpected EOF"
whishper-backend        | 5:34PM ERR Error reading message error="websocket: close 1006 (abnormal closure): unexpected EOF"
whishper-backend        | 5:35PM ERR Error reading message error="websocket: close 1006 (abnormal closure): unexpected EOF"
whishper-backend        | 5:36PM ERR Error reading message error="websocket: close 1006 (abnormal closure): unexpected EOF"
whishper-backend        | 5:37PM ERR Error reading message error="websocket: close 1006 (abnormal closure): unexpected EOF"
whishper-backend        | 5:38PM ERR Error reading message error="websocket: close 1006 (abnormal closure): unexpected EOF"
whisper-api             | INFO:     Started server process [1]
whisper-api             | INFO:     Waiting for application startup.
whisper-api             | INFO:     Application startup complete.
whisper-api             | INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
whisper-api             | Downloading model tiny...
whisper-api             | Model already cached...
whisper-api             | Downloading model small...
whisper-api             | Model already cached...
whisper-api             | INFO:     127.0.0.1:34476 - "GET /healthcheck/ HTTP/1.1" 200 OK
whisper-api             | INFO:     Shutting down
whisper-api             | INFO:     Waiting for application shutdown.
whisper-api             | INFO:     Application shutdown complete.
whisper-api             | INFO:     Finished server process [1]
whisper-api             | INFO:     Started server process [1]
whisper-api             | INFO:     Waiting for application startup.
whisper-api             | INFO:     Application startup complete.
whisper-api             | INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
whisper-api             | Downloading model tiny...
whisper-api             | Model already cached...
whisper-api             | Downloading model small...
whisper-api             | Model already cached...
whisper-api             | INFO:     127.0.0.1:55072 - "GET /healthcheck/ HTTP/1.1" 200 OK
whisper-api             | INFO:     127.0.0.1:43946 - "GET /healthcheck/ HTTP/1.1" 200 OK
whisper-api             | INFO:     127.0.0.1:40994 - "GET /healthcheck/ HTTP/1.1" 200 OK
whisper-api             | INFO:     127.0.0.1:59598 - "GET /healthcheck/ HTTP/1.1" 200 OK
whisper-api             | INFO:     127.0.0.1:33116 - "GET /healthcheck/ HTTP/1.1" 200 OK
whisper-api             | INFO:     127.0.0.1:39294 - "GET /healthcheck/ HTTP/1.1" 200 OK
whisper-api             | INFO:     127.0.0.1:42128 - "GET /healthcheck/ HTTP/1.1" 200 OK
whisper-api             | INFO:     127.0.0.1:46896 - "GET /healthcheck/ HTTP/1.1" 200 OK
thomas-nginx-1          | 172.19.0.1 - - [04/Nov/2023:17:19:15 +0000] "GET /ws/transcriptions HTTP/1.1" 101 0 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36"
thomas-nginx-1          | 172.19.0.1 - - [04/Nov/2023:17:19:15 +0000] "GET /ws/transcriptions HTTP/1.1" 101 0 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36"
thomas-nginx-1          | 172.19.0.1 - - [04/Nov/2023:17:20:16 +0000] "GET /ws/transcriptions HTTP/1.1" 101 0 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36"
thomas-nginx-1          | 172.19.0.1 - - [04/Nov/2023:17:20:16 +0000] "GET /ws/transcriptions HTTP/1.1" 101 0 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36"
thomas-nginx-1          | 172.19.0.1 - - [04/Nov/2023:17:20:37 +0000] "DELETE /api/transcriptions/654674a000a8d73ae9748509 HTTP/1.1" 200 0 "http://localhost:8082/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36"
thomas-nginx-1          | 172.19.0.1 - - [04/Nov/2023:17:20:40 +0000] "GET /ws/transcriptions HTTP/1.1" 101 4 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36"
thomas-nginx-1          | 172.19.0.1 - - [04/Nov/2023:17:20:40 +0000] "GET /ws/transcriptions HTTP/1.1" 101 0 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36"
thomas-nginx-1          | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
thomas-nginx-1          | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
thomas-nginx-1          | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
thomas-nginx-1          | 10-listen-on-ipv6-by-default.sh: info: IPv6 listen already enabled
thomas-nginx-1          | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
thomas-nginx-1          | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
thomas-nginx-1          | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
thomas-nginx-1          | /docker-entrypoint.sh: Configuration complete; ready for start up
thomas-nginx-1          | 172.19.0.3 - - [04/Nov/2023:17:22:22 +0000] "GET /api/transcriptions HTTP/1.1" 200 699768 "-" "undici"
thomas-nginx-1          | 172.19.0.1 - - [04/Nov/2023:17:22:22 +0000] "GET / HTTP/1.1" 200 216535 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36"
thomas-nginx-1          | 172.19.0.1 - - [04/Nov/2023:17:22:24 +0000] "GET /api/transcriptions HTTP/1.1" 200 699768 "http://localhost:8082/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36"
thomas-nginx-1          | 172.19.0.1 - - [04/Nov/2023:17:22:24 +0000] "GET /languages HTTP/1.1" 200 175 "http://localhost:8082/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36"
thomas-nginx-1          | 172.19.0.1 - - [04/Nov/2023:17:22:33 +0000] "GET /ws/transcriptions HTTP/1.1" 101 4 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36"
thomas-nginx-1          | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
thomas-nginx-1          | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
thomas-nginx-1          | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
thomas-nginx-1          | 10-listen-on-ipv6-by-default.sh: info: IPv6 listen already enabled
thomas-nginx-1          | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
thomas-nginx-1          | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
thomas-nginx-1          | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
thomas-nginx-1          | /docker-entrypoint.sh: Configuration complete; ready for start up
thomas-nginx-1          | 172.19.0.5 - - [04/Nov/2023:17:25:22 +0000] "GET /api/transcriptions HTTP/1.1" 200 699768 "-" "undici"
thomas-nginx-1          | 172.19.0.1 - - [04/Nov/2023:17:25:22 +0000] "GET / HTTP/1.1" 200 216518 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36"
thomas-nginx-1          | 172.19.0.1 - - [04/Nov/2023:17:25:24 +0000] "GET /api/transcriptions HTTP/1.1" 200 699768 "http://localhost:8082/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36"
thomas-nginx-1          | 172.19.0.1 - - [04/Nov/2023:17:25:24 +0000] "GET /languages HTTP/1.1" 200 175 "http://localhost:8082/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36"
thomas-nginx-1          | 172.19.0.1 - - [04/Nov/2023:17:26:24 +0000] "GET /ws/transcriptions HTTP/1.1" 101 0 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36"
thomas-nginx-1          | 172.19.0.1 - - [04/Nov/2023:17:27:25 +0000] "GET /ws/transcriptions HTTP/1.1" 101 0 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36"
thomas-nginx-1          | 172.19.0.1 - - [04/Nov/2023:17:28:27 +0000] "GET /ws/transcriptions HTTP/1.1" 101 0 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36"
thomas-nginx-1          | 172.19.0.1 - - [04/Nov/2023:17:29:28 +0000] "GET /ws/transcriptions HTTP/1.1" 101 0 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36"
thomas-nginx-1          | 172.19.0.1 - - [04/Nov/2023:17:30:29 +0000] "GET /ws/transcriptions HTTP/1.1" 101 0 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36"
thomas-nginx-1          | 172.19.0.1 - - [04/Nov/2023:17:31:30 +0000] "GET /ws/transcriptions HTTP/1.1" 101 0 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36"
thomas-nginx-1          | 172.19.0.1 - - [04/Nov/2023:17:32:31 +0000] "GET /ws/transcriptions HTTP/1.1" 101 0 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36"
thomas-nginx-1          | 172.19.0.1 - - [04/Nov/2023:17:33:32 +0000] "GET /ws/transcriptions HTTP/1.1" 101 0 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36"
thomas-nginx-1          | 172.19.0.1 - - [04/Nov/2023:17:34:33 +0000] "GET /ws/transcriptions HTTP/1.1" 101 0 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36"
thomas-nginx-1          | 172.19.0.1 - - [04/Nov/2023:17:35:34 +0000] "GET /ws/transcriptions HTTP/1.1" 101 0 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36"
thomas-nginx-1          | 172.19.0.1 - - [04/Nov/2023:17:36:35 +0000] "GET /ws/transcriptions HTTP/1.1" 101 0 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36"
thomas-nginx-1          | 172.19.0.1 - - [04/Nov/2023:17:37:36 +0000] "GET /ws/transcriptions HTTP/1.1" 101 0 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36"
thomas-nginx-1          | 172.19.0.1 - - [04/Nov/2023:17:38:37 +0000] "GET /ws/transcriptions HTTP/1.1" 101 0 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36"
thomas-nginx-1          | 172.19.0.5 - - [04/Nov/2023:17:38:52 +0000] "GET /api/transcriptions HTTP/1.1" 200 699768 "-" "undici"
thomas-nginx-1          | 172.19.0.1 - - [04/Nov/2023:17:38:52 +0000] "GET / HTTP/1.1" 200 216514 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36"
thomas-nginx-1          | 172.19.0.1 - - [04/Nov/2023:17:38:52 +0000] "GET /ws/transcriptions HTTP/1.1" 101 0 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36"
thomas-nginx-1          | 172.19.0.1 - - [04/Nov/2023:17:38:53 +0000] "GET /api/transcriptions HTTP/1.1" 200 699768 "http://localhost:8082/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36"
thomas-nginx-1          | 172.19.0.1 - - [04/Nov/2023:17:38:53 +0000] "GET /languages HTTP/1.1" 200 175 "http://localhost:8082/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36"
whisper-api             | INFO:     127.0.0.1:33202 - "GET /healthcheck/ HTTP/1.1" 200 OK
whisper-api             | INFO:     127.0.0.1:43926 - "GET /healthcheck/ HTTP/1.1" 200 OK
whisper-api             | INFO:     127.0.0.1:59030 - "GET /healthcheck/ HTTP/1.1" 200 OK
whisper-api             | INFO:     127.0.0.1:47418 - "GET /healthcheck/ HTTP/1.1" 200 OK
whisper-api             | INFO:     127.0.0.1:57418 - "GET /healthcheck/ HTTP/1.1" 200 OK
whisper-api             | INFO:     127.0.0.1:56712 - "GET /healthcheck/ HTTP/1.1" 200 OK
whisper-api             | INFO:     127.0.0.1:47222 - "GET /healthcheck/ HTTP/1.1" 200 OK
whisper-api             | INFO:     127.0.0.1:46632 - "GET /healthcheck/ HTTP/1.1" 200 OK
whisper-api             | INFO:     127.0.0.1:45544 - "GET /healthcheck/ HTTP/1.1" 200 OK
whisper-api             | INFO:     127.0.0.1:46926 - "GET /healthcheck/ HTTP/1.1" 200 OK
whisper-api             | INFO:     127.0.0.1:60998 - "GET /healthcheck/ HTTP/1.1" 200 OK
whisper-api             | INFO:     127.0.0.1:38670 - "GET /healthcheck/ HTTP/1.1" 200 OK
whisper-api             | INFO:     127.0.0.1:33074 - "GET /healthcheck/ HTTP/1.1" 200 OK
whisper-api             | INFO:     127.0.0.1:33284 - "GET /healthcheck/ HTTP/1.1" 200 OK
whisper-api             | INFO:     127.0.0.1:44000 - "GET /healthcheck/ HTTP/1.1" 200 OK
whisper-api             | INFO:     127.0.0.1:50938 - "GET /healthcheck/ HTTP/1.1" 200 OK
whisper-api             | INFO:     127.0.0.1:59838 - "GET /healthcheck/ HTTP/1.1" 200 OK
whisper-api             | INFO:     127.0.0.1:58928 - "GET /healthcheck/ HTTP/1.1" 200 OK
whisper-api             | INFO:     127.0.0.1:50436 - "GET /healthcheck/ HTTP/1.1" 200 OK
whisper-api             | INFO:     127.0.0.1:33762 - "GET /healthcheck/ HTTP/1.1" 200 OK
whisper-api             | INFO:     127.0.0.1:38202 - "GET /healthcheck/ HTTP/1.1" 200 OK
thomas-nginx-1          | 172.19.0.1 - - [04/Nov/2023:17:39:53 +0000] "GET /ws/transcriptions HTTP/1.1" 101 0 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36"
whishper-backend        | 5:39PM ERR Error reading message error="websocket: close 1006 (abnormal closure): unexpected EOF"
whisper-api             | INFO:     127.0.0.1:48182 - "GET /healthcheck/ HTTP/1.1" 200 OK
whisper-api             | INFO:     127.0.0.1:56564 - "GET /healthcheck/ HTTP/1.1" 200 OK
thomas-nginx-1          | 172.19.0.1 - - [04/Nov/2023:17:40:54 +0000] "GET /ws/transcriptions HTTP/1.1" 101 0 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36"
whishper-backend        | 5:40PM ERR Error reading message error="websocket: close 1006 (abnormal closure): unexpected EOF"
whisper-api             | INFO:     127.0.0.1:40554 - "GET /healthcheck/ HTTP/1.1" 200 OK

```

### Docker Compose File

```yaml
version: "3.9"

services:
  mongo:
    image: mongo
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./whishper_data/db_data:/data/db
      - ./whishper_data/db_data/logs/:/var/log/mongodb/
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER:-whishper}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS:-whishper}
    expose:
      - 27017
    command: ['--logpath', '/var/log/mongodb/mongod.log']
    healthcheck:
      test: mongosh --eval 'db.runCommand("ping").ok' --quiet
      interval: 2s
      timeout: 3s
      retries: 5

  translate-cpu:
    container_name: whisper-libretranslate
    profiles: ["cpu"]
    image: libretranslate/libretranslate:latest
    restart: unless-stopped
    volumes:
      - ./whishper_data/libretranslate/data:/home/libretranslate/.local/share
      - ./whishper_data/libretranslate/cache:/home/libretranslate/.local/cache
    env_file:
      - .env
    tty: true
    environment:
      LT_DISABLE_WEB_UI: True
      #LT_UPDATE_MODELS: True
    expose:
      - 5000
    networks:
      default:
        aliases:
          - translate
    healthcheck:
      test: ['CMD-SHELL', './venv/bin/python scripts/healthcheck.py']
      interval: 2s
      timeout: 3s
      retries: 5

  translate-gpu:
    container_name: whisper-libretranslate
    image: libretranslate/libretranslate:latest-cuda
    profiles: ["gpu"]
    restart: unless-stopped
    volumes:
      - ./whishper_data/libretranslate/data:/home/libretranslate/.local/share
      - ./whishper_data/libretranslate/cache:/home/libretranslate/.local/cache
    env_file:
      - .env
    user: root
    tty: true
    environment:
      LT_DISABLE_WEB_UI: True
      LT_LOAD_ONLY: ${LT_LOAD_ONLY:-en,fr,es}
      #LT_UPDATE_MODELS: True
    expose:
      - 5000
    networks:
      default:
        aliases:
          - translate
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
    healthcheck:
      test: ['CMD-SHELL', './venv/bin/python scripts/healthcheck.py']
      interval: 2s
      timeout: 3s
      retries: 5

  transcription-api-cpu:
    container_name: whisper-api
    profiles: ["cpu"]
    image: pluja/whishper-transcription-api:latest
    env_file:
      - .env
    volumes:
      - ./whishper_data/whisper_models:/app/models
      - ./whishper_data/uploads:/app/uploads
    environment:
      - WHISPER_MODELS_DIR=/app/models
      - UPLOAD_DIR=/app/uploads
    networks:
      default:
        aliases:
          - transcription-api
    restart: unless-stopped
    expose:
      - 8000

  transcription-api-gpu:
    container_name: whisper-api
    profiles: ["gpu"]
    image: pluja/whishper-transcription-api:latest-gpu
    env_file:
      - .env
    volumes:
      - ./whishper_data/whisper_models:/app/models
      - ./whishper_data/uploads:/app/uploads
    environment:
      WHISPER_MODELS_DIR: /app/models
      UPLOAD_DIR: /app/uploads
    restart: unless-stopped
    expose:
      - 8000
    networks:
      default:
        aliases:
          - transcription-api
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]

  whishper-backend:
    container_name: whishper-backend
    image: pluja/whishper-backend:latest
    env_file:
      - .env
    volumes:
      - ./whishper_data/uploads:/app/uploads
    restart: unless-stopped
    depends_on:
      mongo:
        condition: service_healthy
    healthcheck:
      test: curl --fail http://localhost:8080/api/transcriptions || exit 1
      interval: 2s
      timeout: 2s
      retries: 5
    expose:
      - 8080

  whishper-frontend:
    container_name: whishper-web
    image: pluja/whishper-frontend:latest
    env_file:
      - .env
    restart: unless-stopped
    environment:
      PUBLIC_INTERNAL_API_HOST: "http://nginx:80"
      PUBLIC_TRANSLATION_API_HOST: ""
      PUBLIC_API_HOST: ${WHISHPER_HOST:-}
      PUBLIC_WHISHPER_PROFILE: ${COMPOSE_PROFILES:-false}
    expose:
      - 3000

  nginx:
    image: nginx:1
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./whishper_data/uploads:/app/uploads
    depends_on:
      whishper-backend:
        condition: service_healthy
    ports:
      - 8082:80    
```
