### ISSUE TITLE
[BUG] Potential Bug - Potential User Error

### ISSUE THREAD

**Issue by eyalspier** [pluja/whishper#49]
## **Description**
I cannot see any languages when attempting to translate. I can only chose from an empty list

### **To Reproduce**
I have the following in my docker-compose.yaml:

```yaml
 whishper-backend:
      container_name: whishper-backend
      image: pluja/whishper-backend:latest
      env_file:
        - ${USERDIR}/docker/whishper_data/.env
      volumes:
        - ${USERDIR}/docker/whishper_data/uploads:/app/uploads
      restart: unless-stopped
      depends_on:
        mongo:
          condition: service_healthy
      healthcheck:
        test: curl --fail http://localhost:8080/api/transcriptions || exit 1
        interval: 2s
        timeout: 2s
        retries: 5
      expose:
        - 8080
    whishper-frontend:
      container_name: whishper-web
      image: pluja/whishper-frontend:latest
      env_file:
        - ${USERDIR}/docker/whishper_data/.env
      restart: unless-stopped
      environment:
        PUBLIC_INTERNAL_API_HOST: "http://nginx:80"
        PUBLIC_TRANSLATION_API_HOST: ""
        PUBLIC_API_HOST: ${WHISHPER_HOST:-}
        PUBLIC_WHISHPER_PROFILE: ${COMPOSE_PROFILES:-false}
      expose:
        - 3000
    nginx:
      image: nginx:1
      container_name: whishper
      restart: unless-stopped
      labels:
        - swag=enable
      volumes:
        - ${USERDIR}/docker/whishper_data/nginx.conf:/etc/nginx/nginx.conf
        - ${USERDIR}/docker/whishper_data/uploads:/app/uploads
      depends_on:
        whishper-backend:
          condition: service_healthy
      ports:
        - 8082:80    
    transcription-api:
      container_name: whisper-api
#      profiles: ["cpu"]
      image: pluja/whishper-transcription-api:latest
      env_file:
        - ${USERDIR}/docker/whishper_data/.env
      volumes:
        - ${USERDIR}/docker/whishper_data/whisper_models:/app/models
        - ${USERDIR}/docker/whishper_data/uploads:/app/uploads
      environment:
        - WHISPER_MODELS_DIR=/app/models
        - UPLOAD_DIR=/app/uploads
      restart: unless-stopped
      expose:
        - 8000
    translate:
      container_name: whisper-libretranslate
#      profiles: ["cpu"]
      image: libretranslate/libretranslate:latest
      restart: unless-stopped
      volumes:
        - ${USERDIR}/docker/whishper_data/libretranslate/data:/home/libretranslate/.local/share
        - ${USERDIR}/docker/whishper_data/libretranslate/cache:/home/libretranslate/.local/cache
      env_file:
        - ${USERDIR}/docker/whishper_data/.env
      tty: true
      environment:
        LT_DISABLE_WEB_UI: "True"
        #LT_UPDATE_MODELS: True
      expose:
        - 5000
      healthcheck:
        test: ['CMD-SHELL', './venv/bin/python scripts/healthcheck.py']
        interval: 2s
        timeout: 3s
        retries: 5
```

And the following simple config:
```
# PROFILE
COMPOSE_PROFILES=cpu # set to 'gpu' if you have GPU with cuda support, read https://whishper.net/guides/gpu

# Libretranslate Configuration
LT_LOAD_ONLY=es,en,fr,nb

# Whisper Configuration
WHISPER_MODELS=tiny,small
WHISHPER_HOST=http://whishper:8082

# Database Configuration
DB_USER=whishper
DB_PASS=whishper
```

As far as I can see this is a base installation for a cpu setup (except for the SWAG label for my reverse proxying of the nginx container and the container names. Everything else works fantastically though!
