### ISSUE TITLE
[Feature] Custom published port for nginx

### ISSUE THREAD

**Issue by biblia19** [pluja/whishper#51]
**Description of the feature you are requesting:**
User can easily to change published port with `.env` file
Maybe duplicate with [[Feature] Specify ports for all services in the .env file](https://github.com/pluja/whishper/issues/4)

**Describe the solution you'd like**
## .env
```
...
# Bottom of the file
# Custom Port Configuration
NGINX_PORT=18082 # (or whatever you want)
```
## docker-compose.yml
```
version: "3.9"

services:
...
  nginx:
    ...
    ports:
      - ${NGINX_PORT:-8082}:80
```

**Additional context**
User can check the port with `docker compose config | grep published`
