### ISSUE TITLE
[BUG] Transcription not working at all  --- SOLVED ---

### ISSUE THREAD

**Issue by mikele1976** [pluja/whishper#65]
## **Description**
Transcription not working at all

### **To Reproduce**
1. Install  easy or manual way (both root or sudo user docker group memeber)
2. just essay to use the web ui with local mp3 files or youtube urls

### Environment
- OS: debian 12 (cat /etc/debian_version -->12.2)
- Browser: Firefox 
- Version: 120 [120.0.1 (64 bits)]
- Hosting: local VM (VMware)

## Logs and Configuration

![image](https://github.com/pluja/whishper/assets/153273048/3be7a408-607d-4715-9976-dfda99235adc)

> docker compose ps
```
 docker compose ps
NAME                     IMAGE                                  COMMAND                                                        SERVICE     CREATED          STATUS                    PORTS
whishper                 pluja/whishper:latest                  "supervisord -c /etc/supervisor/conf.d/supervisord.conf"       whishper    20 minutes ago   Up 20 minutes             3000/tcp, 5000/tcp, 8080/tcp, 0.0.0.0:8082->80/tcp, :::8082->80/tcp
whishper-mongo-1         mongo                                  "docker-entrypoint.sh --logpath /var/log/mongodb/mongod.log"   mongo       20 minutes ago   Up 20 minutes             27017/tcp
whisper-libretranslate   libretranslate/libretranslate:latest   "./venv/bin/libretranslate --host 0.0.0.0"                     translate   20 minutes ago   Up 20 minutes (healthy)   5000/tcp
```

### Docker Compose Logs

> Run the following command in the project folder, force the error, and paste the logs below: `docker compose logs -f --tail 50`

```
whisper-libretranslate  | Updating language models
whisper-libretranslate  | Found 84 models
whisper-libretranslate  | Keep 4 models
whisper-libretranslate  | Downloading English → French (1.9) ...
whisper-libretranslate  | Downloading English → Spanish (1.0) ...
whisper-libretranslate  | Downloading French → English (1.9) ...
whisper-libretranslate  | Downloading Spanish → English (1.0) ...
whisper-libretranslate  | Loaded support for 3 languages (4 models total)!
whisper-libretranslate  | Running on http://0.0.0.0:5000
whishper                | 2023-12-08 13:16:48,413 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
whishper                | 2023-12-08 13:16:48,419 INFO supervisord started with pid 1
whishper                | 2023-12-08 13:16:49,423 INFO spawned: 'backend' with pid 7
whishper                | 2023-12-08 13:16:49,434 INFO spawned: 'frontend' with pid 8
whishper                | 2023-12-08 13:16:49,446 INFO spawned: 'nginx' with pid 9
whishper                | 2023-12-08 13:16:49,464 INFO spawned: 'transcription' with pid 10
whishper                | 2023-12-08 13:16:51,132 INFO success: backend entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
whishper                | 2023-12-08 13:16:51,133 INFO success: frontend entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
whishper                | 2023-12-08 13:16:51,134 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
whishper                | 2023-12-08 13:16:51,134 INFO success: transcription entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
whishper-mongo-1        | {"t":{"$date":"2023-12-08T13:16:56.503+00:00"},"s":"I",  "c":"SHARDING", "id":4784902, "ctx":"SignalHandler","msg":"Shutting down the WaitForMajorityService"}
whishper-mongo-1        | {"t":{"$date":"2023-12-08T13:16:56.504+00:00"},"s":"I",  "c":"CONTROL",  "id":4784903, "ctx":"SignalHandler","msg":"Shutting down the LogicalSessionCache"}
whishper-mongo-1        | {"t":{"$date":"2023-12-08T13:16:56.504+00:00"},"s":"I",  "c":"NETWORK",  "id":20562,   "ctx":"SignalHandler","msg":"Shutdown: going to close listening sockets"}
whishper-mongo-1        | {"t":{"$date":"2023-12-08T13:16:56.509+00:00"},"s":"I",  "c":"NETWORK",  "id":23017,   "ctx":"listener","msg":"removing socket file","attr":{"path":"/tmp/mongodb-27017.sock"}}
whishper-mongo-1        | {"t":{"$date":"2023-12-08T13:16:56.509+00:00"},"s":"I",  "c":"NETWORK",  "id":4784905, "ctx":"SignalHandler","msg":"Shutting down the global connection pool"}
whishper-mongo-1        | {"t":{"$date":"2023-12-08T13:16:56.509+00:00"},"s":"I",  "c":"CONTROL",  "id":4784906, "ctx":"SignalHandler","msg":"Shutting down the FlowControlTicketholder"}
whishper-mongo-1        | {"t":{"$date":"2023-12-08T13:16:56.509+00:00"},"s":"I",  "c":"-",        "id":20520,   "ctx":"SignalHandler","msg":"Stopping further Flow Control ticket acquisitions."}
whishper-mongo-1        | {"t":{"$date":"2023-12-08T13:16:56.509+00:00"},"s":"I",  "c":"CONTROL",  "id":4784908, "ctx":"SignalHandler","msg":"Shutting down the PeriodicThreadToAbortExpiredTransactions"}
whishper-mongo-1        | {"t":{"$date":"2023-12-08T13:16:56.509+00:00"},"s":"I",  "c":"REPL",     "id":4784909, "ctx":"SignalHandler","msg":"Shutting down the ReplicationCoordinator"}
whishper-mongo-1        | {"t":{"$date":"2023-12-08T13:16:56.509+00:00"},"s":"I",  "c":"SHARDING", "id":4784910, "ctx":"SignalHandler","msg":"Shutting down the ShardingInitializationMongoD"}
whishper-mongo-1        | {"t":{"$date":"2023-12-08T13:16:56.509+00:00"},"s":"I",  "c":"REPL",     "id":4784911, "ctx":"SignalHandler","msg":"Enqueuing the ReplicationStateTransitionLock for shutdown"}
whishper-mongo-1        | {"t":{"$date":"2023-12-08T13:16:56.509+00:00"},"s":"I",  "c":"-",        "id":4784912, "ctx":"SignalHandler","msg":"Killing all operations for shutdown"}
whishper-mongo-1        | {"t":{"$date":"2023-12-08T13:16:56.509+00:00"},"s":"I",  "c":"-",        "id":4695300, "ctx":"SignalHandler","msg":"Interrupted all currently running operations","attr":{"opsKilled":3}}
whishper-mongo-1        | {"t":{"$date":"2023-12-08T13:16:56.509+00:00"},"s":"I",  "c":"TENANT_M", "id":5093807, "ctx":"SignalHandler","msg":"Shutting down all TenantMigrationAccessBlockers on global shutdown"}
whishper-mongo-1        | {"t":{"$date":"2023-12-08T13:16:56.509+00:00"},"s":"I",  "c":"ASIO",     "id":22582,   "ctx":"TenantMigrationBlockerNet","msg":"Killing all outstanding egress activity."}
whishper-mongo-1        | {"t":{"$date":"2023-12-08T13:16:56.509+00:00"},"s":"I",  "c":"ASIO",     "id":6529201, "ctx":"SignalHandler","msg":"Network interface redundant shutdown","attr":{"state":"Stopped"}}
whishper-mongo-1        | {"t":{"$date":"2023-12-08T13:16:56.509+00:00"},"s":"I",  "c":"ASIO",     "id":22582,   "ctx":"SignalHandler","msg":"Killing all outstanding egress activity."}
whishper-mongo-1        | {"t":{"$date":"2023-12-08T13:16:56.509+00:00"},"s":"I",  "c":"COMMAND",  "id":4784913, "ctx":"SignalHandler","msg":"Shutting down all open transactions"}
whishper-mongo-1        | {"t":{"$date":"2023-12-08T13:16:56.509+00:00"},"s":"I",  "c":"REPL",     "id":4784914, "ctx":"SignalHandler","msg":"Acquiring the ReplicationStateTransitionLock for shutdown"}
whishper-mongo-1        | {"t":{"$date":"2023-12-08T13:16:56.509+00:00"},"s":"I",  "c":"INDEX",    "id":4784915, "ctx":"SignalHandler","msg":"Shutting down the IndexBuildsCoordinator"}
whishper-mongo-1        | {"t":{"$date":"2023-12-08T13:16:56.509+00:00"},"s":"I",  "c":"NETWORK",  "id":4784918, "ctx":"SignalHandler","msg":"Shutting down the ReplicaSetMonitor"}
whishper-mongo-1        | {"t":{"$date":"2023-12-08T13:16:56.509+00:00"},"s":"I",  "c":"SHARDING", "id":4784921, "ctx":"SignalHandler","msg":"Shutting down the MigrationUtilExecutor"}
whishper-mongo-1        | {"t":{"$date":"2023-12-08T13:16:56.510+00:00"},"s":"I",  "c":"ASIO",     "id":22582,   "ctx":"MigrationUtil-TaskExecutor","msg":"Killing all outstanding egress activity."}
whishper-mongo-1        | {"t":{"$date":"2023-12-08T13:16:56.510+00:00"},"s":"I",  "c":"COMMAND",  "id":4784923, "ctx":"SignalHandler","msg":"Shutting down the ServiceEntryPoint"}
whishper-mongo-1        | {"t":{"$date":"2023-12-08T13:16:56.510+00:00"},"s":"I",  "c":"CONTROL",  "id":4784927, "ctx":"SignalHandler","msg":"Shutting down the HealthLog"}
whishper-mongo-1        | {"t":{"$date":"2023-12-08T13:16:56.510+00:00"},"s":"I",  "c":"CONTROL",  "id":4784928, "ctx":"SignalHandler","msg":"Shutting down the TTL monitor"}
whishper-mongo-1        | {"t":{"$date":"2023-12-08T13:16:56.510+00:00"},"s":"I",  "c":"INDEX",    "id":3684100, "ctx":"SignalHandler","msg":"Shutting down TTL collection monitor thread"}
whishper-mongo-1        | {"t":{"$date":"2023-12-08T13:16:56.510+00:00"},"s":"I",  "c":"INDEX",    "id":3684101, "ctx":"SignalHandler","msg":"Finished shutting down TTL collection monitor thread"}
whishper-mongo-1        | {"t":{"$date":"2023-12-08T13:16:56.510+00:00"},"s":"I",  "c":"CONTROL",  "id":6278511, "ctx":"SignalHandler","msg":"Shutting down the Change Stream Expired Pre-images Remover"}
whishper-mongo-1        | {"t":{"$date":"2023-12-08T13:16:56.510+00:00"},"s":"I",  "c":"CONTROL",  "id":4784929, "ctx":"SignalHandler","msg":"Acquiring the global lock for shutdown"}
whishper-mongo-1        | {"t":{"$date":"2023-12-08T13:16:56.510+00:00"},"s":"I",  "c":"CONTROL",  "id":4784930, "ctx":"SignalHandler","msg":"Shutting down the storage engine"}
whishper-mongo-1        | {"t":{"$date":"2023-12-08T13:16:56.510+00:00"},"s":"I",  "c":"STORAGE",  "id":22320,   "ctx":"SignalHandler","msg":"Shutting down journal flusher thread"}
whishper-mongo-1        | {"t":{"$date":"2023-12-08T13:16:56.510+00:00"},"s":"I",  "c":"STORAGE",  "id":22321,   "ctx":"SignalHandler","msg":"Finished shutting down journal flusher thread"}
whishper-mongo-1        | {"t":{"$date":"2023-12-08T13:16:56.510+00:00"},"s":"I",  "c":"STORAGE",  "id":22322,   "ctx":"SignalHandler","msg":"Shutting down checkpoint thread"}
whishper-mongo-1        | {"t":{"$date":"2023-12-08T13:16:56.510+00:00"},"s":"I",  "c":"STORAGE",  "id":22323,   "ctx":"SignalHandler","msg":"Finished shutting down checkpoint thread"}
whishper-mongo-1        | {"t":{"$date":"2023-12-08T13:16:56.510+00:00"},"s":"I",  "c":"STORAGE",  "id":22261,   "ctx":"SignalHandler","msg":"Timestamp monitor shutting down"}
whishper-mongo-1        | {"t":{"$date":"2023-12-08T13:16:56.510+00:00"},"s":"I",  "c":"STORAGE",  "id":20282,   "ctx":"SignalHandler","msg":"Deregistering all the collections"}
whishper-mongo-1        | {"t":{"$date":"2023-12-08T13:16:56.510+00:00"},"s":"I",  "c":"STORAGE",  "id":22317,   "ctx":"SignalHandler","msg":"WiredTigerKVEngine shutting down"}
whishper-mongo-1        | {"t":{"$date":"2023-12-08T13:16:56.510+00:00"},"s":"I",  "c":"STORAGE",  "id":22318,   "ctx":"SignalHandler","msg":"Shutting down session sweeper thread"}
whishper-mongo-1        | {"t":{"$date":"2023-12-08T13:16:56.510+00:00"},"s":"I",  "c":"STORAGE",  "id":22319,   "ctx":"SignalHandler","msg":"Finished shutting down session sweeper thread"}
whishper-mongo-1        | {"t":{"$date":"2023-12-08T13:16:56.518+00:00"},"s":"I",  "c":"STORAGE",  "id":4795902, "ctx":"SignalHandler","msg":"Closing WiredTiger","attr":{"closeConfig":"leak_memory=true,use_timestamp=false,"}}
whishper-mongo-1        | {"t":{"$date":"2023-12-08T13:16:56.578+00:00"},"s":"I",  "c":"STORAGE",  "id":4795901, "ctx":"SignalHandler","msg":"WiredTiger closed","attr":{"durationMillis":60}}
whishper-mongo-1        | {"t":{"$date":"2023-12-08T13:16:56.578+00:00"},"s":"I",  "c":"STORAGE",  "id":22279,   "ctx":"SignalHandler","msg":"shutdown: removing fs lock..."}
whishper-mongo-1        | {"t":{"$date":"2023-12-08T13:16:56.578+00:00"},"s":"I",  "c":"-",        "id":4784931, "ctx":"SignalHandler","msg":"Dropping the scope cache for shutdown"}
whishper-mongo-1        | {"t":{"$date":"2023-12-08T13:16:56.578+00:00"},"s":"I",  "c":"FTDC",     "id":20626,   "ctx":"SignalHandler","msg":"Shutting down full-time diagnostic data capture"}
whishper-mongo-1        | {"t":{"$date":"2023-12-08T13:16:56.581+00:00"},"s":"I",  "c":"CONTROL",  "id":20565,   "ctx":"SignalHandler","msg":"Now exiting"}
whishper-mongo-1        | {"t":{"$date":"2023-12-08T13:16:56.581+00:00"},"s":"I",  "c":"CONTROL",  "id":23138,   "ctx":"SignalHandler","msg":"Shutting down","attr":{"exitCode":0}}
whishper-mongo-1        |
whishper-mongo-1        | MongoDB init process complete; ready for start up.
whishper-mongo-1        |
```

### Docker Compose File

```yaml

version: "3.9"

services:
  mongo:
    image: mongo
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./whishper_data/db_data:/data/db
      - ./whishper_data/db_data/logs/:/var/log/mongodb/
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER:-whishper}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS:-whishper}
    expose:
      - 27017
    command: ['--logpath', '/var/log/mongodb/mongod.log']

  translate:
    container_name: whisper-libretranslate
    image: libretranslate/libretranslate:latest
    restart: unless-stopped
    volumes:
      - ./whishper_data/libretranslate/data:/home/libretranslate/.local/share
      - ./whishper_data/libretranslate/cache:/home/libretranslate/.local/cache
    env_file:
      - .env
    tty: true
    environment:
      LT_DISABLE_WEB_UI: True
      LT_UPDATE_MODELS: True
    expose:
      - 5000
    networks:
      default:
        aliases:
          - translate
    healthcheck:
      test: ['CMD-SHELL', './venv/bin/python scripts/healthcheck.py']
      interval: 2s
      timeout: 3s
      retries: 5

  whishper:
    pull_policy: always
    image: pluja/whishper:${WHISHPER_VERSION:-latest}
    env_file:
      - .env
    volumes:
      - ./whishper_data/uploads:/app/uploads
      - ./whishper_data/logs:/var/log/whishper
    container_name: whishper
    restart: unless-stopped
    networks:
      default:
        aliases:
          - whishper
    ports:
      - 8082:80
    depends_on:
      - mongo
      - translate
    environment:
      PUBLIC_INTERNAL_API_HOST: "http://127.0.0.1:80"
      PUBLIC_TRANSLATION_API_HOST: ""
      PUBLIC_API_HOST: ${WHISHPER_HOST:-}
      PUBLIC_WHISHPER_PROFILE: cpu
      WHISPER_MODELS_DIR: /app/models
      UPLOAD_DIR: /app/uploads


```
.env
```
# Libretranslate Configuration
## Check out https://github.com/LibreTranslate/LibreTranslate#configuration-parameters for more libretranslate configuration options
LT_LOAD_ONLY=es,en,fr

# Whisper Configuration
WHISPER_MODELS=tiny,small
WHISHPER_HOST=http://127.0.0.1:8082

# Database Configuration
DB_USER=whishper
DB_PASS=whishper
```
nginx.conf 
```
events {
    worker_connections 1024;
}

http {
    gzip on;

    server {
        listen 80;

        location /api/video {
            alias /app/uploads/;
        }

        location /languages {
            proxy_pass http://translate:5000;
        }

        location /api {
            client_max_body_size 0;
            proxy_pass http://127.0.0.1:8080;
        }

        location /ws {
            proxy_pass http://127.0.0.1:8080;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }

        location / {
            proxy_pass http://127.0.0.1:3000;
        }
    }
}
```

**Comment by xvag** [comment]
I can confirm the exactly same behavior. Deployment done without errors, all logs are not showing any errors. It just doesn't do anything. 
(Same issue here i guess: https://github.com/pluja/whishper/issues/61)

**Comment by originade** [comment]
Same here. Running on Windows 11 with manual installation. I can see web UI but I get an error when uploading a file and then a "Waiting for transcription" on the file name, but no transcription occurs.

**Comment by vanderheyde** [comment]
Experiencing the same issue on Debian 11 using the quick install setup.

**Comment by tdobson** [comment]
I've been able to use CPU on Debian 12 (install via docker), but GPU loads are now not appearing to work and fail straight away.

$ uname -a
Linux tragicomix 6.4.0-0.deb12.2-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.4.4-3~bpo12+1 (2023-08-08) x86_64 GNU/Linux
$ cat /etc/debian_version 
12.4

**Comment by mikele1976** [comment]
> I've been able to use CPU on Debian 12 (install via docker), but GPU loads are now not appearing to work and fail straight away.
> 
> $ uname -a Linux tragicomix 6.4.0-0.deb12.2-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.4.4-3~bpo12+1 (2023-08-08) x86_64 GNU/Linux $ cat /etc/debian_version 12.4

Hi,
    could you share your configuration files:
docker-compose-yml, nginx.conf and .env 

thans

**Comment by zezretro** [comment]
I confirm the same behavior on debian 11. Fresh install via docker, once you click start the dialog does away and nothing happens. Can not find anything in the logs yet

**Comment by mikele1976** [comment]
HI everyone,
     i tried also with ferret option 
docker-compose.override.yml, compiled with the command docker compose up -d --pull=always

```
version: "3.9"

services:
  postgres:
    image: postgres
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER:-whishper}
      - POSTGRES_PASSWORD=${DB_PASS:-whishper}
      - POSTGRES_DB=whishper
    volumes:
      - ./whishper_data/db_data/ferret:/var/lib/postgresql/data

  mongo:
    image: ghcr.io/ferretdb/ferretdb
    restart: on-failure
    expose:
      - 27017
    env_file:
      - .env
    environment:
      - FERRETDB_POSTGRESQL_URL=postgres://${DB_USER:-whishper}:${DB_PASS:-whishper}@postgres:5432/whishper
    command: ["--telemetry=disable"]

  whishper:
    environment:
      FERRETDB_ENABLED: "true"
```
and i got the same result, the web ui is working great but when i tried to use it nothing happens.

docker compose ps 

```
NAME                     IMAGE                                  COMMAND
   SERVICE     CREATED         STATUS                   PORTS
whishper                 pluja/whishper:latest                  "supervisord -c /etc/supervisor/conf.d/supervisord.conf"   whishper    6 minutes ago   Up 6 minutes             3000/tcp, 5000/tcp, 8080/tcp, 0.0.0.0:8082->80/tcp, :::8082->80/tcp
whisper-libretranslate   libretranslate/libretranslate:latest   "./venv/bin/libretranslate --host 0.0.0.0"
   translate   6 minutes ago   Up 6 minutes (healthy)   5000/tcp
whsp-mongo-1             ghcr.io/ferretdb/ferretdb              "/ferretdb --telemetry=disable"
   mongo       6 minutes ago   Up 6 minutes             8080/tcp, 27017-27018/tcp
whsp-postgres-1          postgres                               "docker-entrypoint.sh postgres"
   postgres    6 minutes ago   Up 6 minutes             5432/tcp
```
I did this test in order to prove that it is not a matter related to a missing avx support .
