### ISSUE TITLE
[BUG] Newest version of Whishper can no longer be  proxied using SWAG for Cloudflare Tunnels

### ISSUE THREAD

**Issue by eyalspier** [pluja/whishper#66]
## **Description**
I have updated the whishper implementation using the new combined structure, and it all works perfectly on my local network at port 8082. When I attempt to add this to my cloudflare tunnel setup using swag, the main page loads but I cannot successfully add new files, cannot download already added transcriptions, and cannot translate.
All I get are loading windows:
![image](https://github.com/pluja/whishper/assets/26817822/f430e94f-0529-4a21-a06d-e1f12856355f)

### **To Reproduce**
1. Install whishper as per the directions using docker-compose
2. Add the argument: labels: -swag=enable to the docker compose file
4. access the app at whishper.yourdomain.com
5. Attempt to download an existing file

### **Expected behavior**
The tunnelled version should work the same as the local version

### Environment
- OS: Ubuntu
- Browser: Chrome
- Hosting: [Local vs Tunnel]

### Docker Compose Logs

```
dockerproxy             | 172.19.0.20:55936 [10/Dec/2023:07:20:00.777] dockerfrontend dockerbackend/dockersocket 0/0/0/0/0 200 8536 - - ---- 1/1/0/0/0 0/0 "GET /v1.43/containers/whishper/json HTTP/1.1"
swag                    | **** New container whishper detected, will generate new conf. ****
swag                    | **** No preset proxy conf found for whishper, generating from scratch ****
swag                    | **** Setting upstream address whishper for whishper ****
swag                    | **** Setting port 3000 for whishper ****
swag                    | **** Setting proto http for whishper ****
swag                    | **** Setting url whishper.* for whishper ****
whishper                | 2023-12-10 07:10:04,120 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
whishper                | 2023-12-10 07:10:04,121 INFO supervisord started with pid 1
whishper                | 2023-12-10 07:10:05,125 INFO spawned: 'backend' with pid 7
whishper                | 2023-12-10 07:10:05,129 INFO spawned: 'frontend' with pid 8
whishper                | 2023-12-10 07:10:05,133 INFO spawned: 'nginx' with pid 9
whishper                | 2023-12-10 07:10:05,137 INFO spawned: 'transcription' with pid 10
whishper                | 2023-12-10 07:10:06,336 INFO success: backend entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
whishper                | 2023-12-10 07:10:06,336 INFO success: frontend entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
whishper                | 2023-12-10 07:10:06,336 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
whishper                | 2023-12-10 07:10:06,336 INFO success: transcription entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
dockerproxy             | 172.19.0.20:43398 [10/Dec/2023:07:21:00.777] dockerfrontend dockerbackend/dockersocket 0/0/0/0/0 200 8536 - - ---- 1/1/0/0/0 0/0 "GET /v1.43/containers/whishper/js
```

### Docker Compose File

```yaml
mongo:
        image: mongo
        env_file:
          - ${USERDIR}/docker/whishper_data/.env
        restart: unless-stopped
        volumes:
          - ${USERDIR}/docker/whishper_data/db_data:/data/db
          - ${USERDIR}/docker/whishper_data/db_data/logs/:/var/log/mongodb/
        environment:
          MONGO_INITDB_ROOT_USERNAME: ${DB_USER:-whishper}
          MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS:-whishper}
        expose:
          - 27017
        command: ['--logpath', '/var/log/mongodb/mongod.log']
    translate:
      container_name: whisper-libretranslate
      image: libretranslate/libretranslate:latest
      restart: unless-stopped
      volumes:
        - ${USERDIR}/docker/whishper_data/libretranslate/data:/home/libretranslate/.local/share
        - ${USERDIR}/docker/whishper_data/libretranslate/cache:/home/libretranslate/.local/cache
      env_file:
        - ${USERDIR}/docker/whishper_data/.env
      tty: true
      environment:
        LT_DISABLE_WEB_UI: "True"
        LT_UPDATE_MODELS: "True"
      expose:
        - 5000
      networks:
        default:
          aliases:
            - translate
      healthcheck:
        test: ['CMD-SHELL', './venv/bin/python scripts/healthcheck.py']
        interval: 2s
        timeout: 3s
        retries: 5
    whishper:
      pull_policy: always
      labels:
        - swag=enable
      image: pluja/whishper:${WHISHPER_VERSION:-latest}
      env_file:
        - ${USERDIR}/docker/whishper_data/.env
      volumes:
        - ${USERDIR}/docker/whishper_data/uploads:/app/uploads
        - ${USERDIR}/docker/whishper_data/logs:/var/log/whishper
      container_name: whishper
      restart: unless-stopped
      networks:
        default:
          aliases:
            - whishper
      ports:
        - 8082:80
      depends_on:
        - mongo
        - translate
      environment:
        PUBLIC_INTERNAL_API_HOST: "http://127.0.0.1:80"
        PUBLIC_TRANSLATION_API_HOST: ""
        PUBLIC_API_HOST: ${WHISHPER_HOST:-}
        PUBLIC_WHISHPER_PROFILE: cpu
        WHISPER_MODELS_DIR: /app/models
        UPLOAD_DIR: /app/uploads 
```
