### ISSUE TITLE
[BUG] Couldn't save Error

### ISSUE THREAD

**Issue by xtrembug** [pluja/whishper#78]
## **Description**
After some time I get the error "Couldn't save"
![whishper](https://github.com/pluja/whishper/assets/44767337/8778602c-0eec-4d6f-aba6-79420867498a)

### **To Reproduce**
1. Edit your transcript
2. Doubleclick on the preview audio/video
3. Close full screen
4. audio/video dissapears (I don't know if that has anything to do with it)
![whishper2](https://github.com/pluja/whishper/assets/44767337/7274af6e-45d0-4194-821d-382bed4f49d8)
5. Do some edits
6. After some time "Couldn't save"

### **Expected behavior**
That I can save my project :)

### Environment
- OS: Win 10
- Browser: Firefox 
- Version: 121.0.1 (64-Bit)
- Hosting: root Server 16GB Ram, 6 CPU, AMD EPYC™ 7702 / Debian 12 / traefik 2.10.7

## Logs and Configuration

#  tail -f backend.err.log
```
7:18PM ERR Error parsing JSON body error="json: float unexpected end of JSON input"
7:18PM ERR Error handling PATCH /api/transcriptions error="Bad request"
7:18PM ERR Error parsing JSON body error="json: float unexpected end of JSON input"
7:18PM ERR Error handling PATCH /api/transcriptions error="Bad request"
7:19PM ERR Error parsing JSON body error="json: float unexpected end of JSON input"
7:19PM ERR Error handling PATCH /api/transcriptions error="Bad request"
7:19PM ERR Error parsing JSON body error="json: float unexpected end of JSON input"
7:19PM ERR Error handling PATCH /api/transcriptions error="Bad request"
7:20PM ERR Error parsing JSON body error="json: float unexpected end of JSON input"
7:20PM ERR Error handling PATCH /api/transcriptions error="Bad request"
7:20PM ERR Error parsing JSON body error="json: float unexpected end of JSON input"
7:20PM ERR Error handling PATCH /api/transcriptions error="Bad request"
7:21PM ERR Error parsing JSON body error="json: float unexpected end of JSON input"
7:21PM ERR Error handling PATCH /api/transcriptions error="Bad request"
```

# tail -f frontend.err.log
```
Error: Not found: /favicon.ico
    at resolve (file:///app/frontend/server/index.js:3654:18)
    at resolve (file:///app/frontend/server/index.js:3481:34)
    at #options.hooks.handle (file:///app/frontend/server/index.js:3720:61)
    at respond (file:///app/frontend/server/index.js:3479:43)
Error: Not found: /wp-admin/install.php
    at resolve (file:///app/frontend/server/index.js:3654:18)
    at resolve (file:///app/frontend/server/index.js:3481:34)
    at #options.hooks.handle (file:///app/frontend/server/index.js:3720:61)
    at respond (file:///app/frontend/server/index.js:3479:43)
```

# tail -f nginx.err.log
`EMPTY`

# tail -f transcription.err.log
```
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
An error occured while synchronizing the model Systran/faster-whisper-medium from the Hugging Face Hub:
Cannot find an appropriate cached snapshot folder for the specified revision on the local disk and outgoing traffic has been disabled. To enable repo look-ups and downloads online, pass 'local_files_only=False' as input.
Trying to load the model directly from the local cache, if it exists.
config.json: 100%|██████████| 2.26k/2.26k [00:00<00:00, 10.1MB/s]
vocabulary.txt: 100%|██████████| 460k/460k [00:00<00:00, 8.39MB/s]
tokenizer.json: 100%|██████████| 2.20M/2.20M [00:00<00:00, 4.47MB/s]
model.bin: 100%|██████████| 1.53G/1.53G [00:06<00:00, 230MB/s]
```

### Docker Compose Logs

```
whishper-mongo-1         | {"t":{"$date":"2024-01-16T20:17:46.533Z"},"s":"I",  "c":"CONTROL",  "id":20697,   "ctx":"main","msg":"Renamed existing log file","attr":{"oldLogPath":"/var/log/mongodb/mongod.log","newLogPath":"/var/log/mongodb/mongod.log.2024-01-16T20-17-46"}}
whishper-libretranslate  | Running on http://0.0.0.0:5000
whishper                 | 2024-01-16 20:17:47,093 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
whishper                 | 2024-01-16 20:17:47,095 INFO supervisord started with pid 1
whishper                 | 2024-01-16 20:17:48,097 INFO spawned: 'backend' with pid 7
whishper                 | 2024-01-16 20:17:48,100 INFO spawned: 'frontend' with pid 8
whishper                 | 2024-01-16 20:17:48,102 INFO spawned: 'nginx' with pid 9
whishper                 | 2024-01-16 20:17:48,104 INFO spawned: 'transcription' with pid 10
whishper                 | 2024-01-16 20:17:49,345 INFO success: backend entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
whishper                 | 2024-01-16 20:17:49,346 INFO success: frontend entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
whishper                 | 2024-01-16 20:17:49,346 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
whishper                 | 2024-01-16 20:17:49,346 INFO success: transcription entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

### Docker Compose File

```
version: "3.9"

services:
  mongo:
    image: mongo
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./whishper_data/db_data:/data/db
      - ./whishper_data/db_data/logs/:/var/log/mongodb/
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER:-whishper}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS:-whishper}
#    expose:
#      - 27017
    command: ['--logpath', '/var/log/mongodb/mongod.log']
    networks:   #NEW
      default: #NEW

  translate:
    container_name: whishper-libretranslate #h ergänzt
    image: libretranslate/libretranslate:latest
    restart: unless-stopped
    volumes:
      - ./whishper_data/libretranslate/data:/home/libretranslate/.local/share
      - ./whishper_data/libretranslate/cache:/home/libretranslate/.local/cache
    env_file:
      - .env
    tty: true
    environment:
      LT_DISABLE_WEB_UI: True
    #  LT_UPDATE_MODELS: True
#    expose:
#      - 5000
    networks:
      - default #:
#        aliases:
#          - translate
    healthcheck:
      test: ['CMD-SHELL', './venv/bin/python scripts/healthcheck.py']
      interval: 2s
      timeout: 3s
      retries: 5

  whishper:
    pull_policy: always
    image: pluja/whishper:${WHISHPER_VERSION:-latest}
    env_file:
      - .env
    volumes:
      - ./whishper_data/uploads:/app/uploads
      - ./whishper_data/logs:/var/log/whishper
    container_name: whishper
    restart: unless-stopped
    networks:
      - proxy
      - default
#        aliases:
#          - whishper
    #ports:
    #  - 8082:80
    depends_on:
      - mongo
      - translate
    environment:
      PUBLIC_INTERNAL_API_HOST: "http://127.0.0.1:80"
      PUBLIC_TRANSLATION_API_HOST: ""
      PUBLIC_API_HOST: ${WHISHPER_HOST:-}
      PUBLIC_WHISHPER_PROFILE: cpu
      WHISPER_MODELS_DIR: /app/models
      UPLOAD_DIR: /app/uploads
      CPU_THREADS: 4
    labels:
      traefik.enable: "true"
      traefik.http.routers.whishper.entrypoints: websecure
      traefik.http.routers.whishper.rule: Host(`$WHISHPER_TRAEFIK_HOST`)
      traefik.http.routers.whishper.tls: "true"
      traefik.http.routers.whishper.tls.certresolver: http_resolver
      traefik.http.routers.whishper.service: whishper
      traefik.http.services.whishper.loadbalancer.server.port: "80"
      traefik.http.routers.whishper.middlewares: default@file
      traefik.docker.network: proxy
networks: #NEW
  proxy:
    external: true
```
