### ISSUE TITLE
[BUG] Installation fail due to an not existed folder for supervisord

### ISSUE THREAD

**Issue by rxi-canarytech** [pluja/whishper#89]
## **Description**
The installation fail due to an error in setting up logger in supervisord. Maybe related to this issue https://github.com/Supervisor/supervisor/issues/120

### **To Reproduce**
1. Go to Unraid Docker Compose Manager
2. Copy&paste [docker-compose.gpu.yml](https://github.com/pluja/whishper/blob/main/docker-compose.gpu.yml) to compose file
3. Click compose up and wait

### **Expected behavior**
The installation success.

### Environment
- OS: Unraid 6.12

### Docker Compose Logs
```
whisper-libretranslate  | Updating language models
whisper-libretranslate  | Found 86 models
whisper-libretranslate  | Keep 4 models
whisper-libretranslate  | Downloading English → French (1.9) ...
whisper-libretranslate  | Downloading English → Spanish (1.0) ...
whisper-libretranslate  | Downloading French → English (1.9) ...
whisper-libretranslate  | Downloading Spanish → English (1.0) ...
whisper-libretranslate  | Loaded support for 3 languages (4 models total)!
whisper-libretranslate  | Running on http://0.0.0.0:5000
whishper                | Error: The directory named as part of the path /var/log/whishper/transcription.out.log does not exist in section 'program:transcription' (file: '/etc/supervisor/conf.d/supervisord.conf')
whishper                | For help, use /usr/bin/supervisord -h
whishper                | Error: The directory named as part of the path /var/log/whishper/transcription.out.log does not exist in section 'program:transcription' (file: '/etc/supervisor/conf.d/supervisord.conf')
whishper                | For help, use /usr/bin/supervisord -h
whishper                | Error: The directory named as part of the path /var/log/whishper/transcription.out.log does not exist in section 'program:transcription' (file: '/etc/supervisor/conf.d/supervisord.conf')
whishper                | For help, use /usr/bin/supervisord -h
whishper                | Error: The directory named as part of the path /var/log/whishper/transcription.out.log does not exist in section 'program:transcription' (file: '/etc/supervisor/conf.d/supervisord.conf')
whishper                | For help, use /usr/bin/supervisord -h
whishper                | Error: The directory named as part of the path /var/log/whishper/transcription.out.log does not exist in section 'program:transcription' (file: '/etc/supervisor/conf.d/supervisord.conf')
whishper                | For help, use /usr/bin/supervisord -h
whishper                | Error: The directory named as part of the path /var/log/whishper/transcription.out.log does not exist in section 'program:transcription' (file: '/etc/supervisor/conf.d/supervisord.conf')
whishper                | For help, use /usr/bin/supervisord -h
whishper                | Error: The directory named as part of the path /var/log/whishper/transcription.out.log does not exist in section 'program:transcription' (file: '/etc/supervisor/conf.d/supervisord.conf')
whishper                | For help, use /usr/bin/supervisord -h
whishper exited with code 2
whishper exited with code 2
whishper exited with code 2
whishper                | Error: The directory named as part of the path /var/log/whishper/transcription.out.log does not exist in section 'program:transcription' (file: '/etc/supervisor/conf.d/supervisord.conf')
whishper                | For help, use /usr/bin/supervisord -h
whishper exited with code 2
whishper                | Error: The directory named as part of the path /var/log/whishper/transcription.out.log does not exist in section 'program:transcription' (file: '/etc/supervisor/conf.d/supervisord.conf')
whishper                | For help, use /usr/bin/supervisord -h
whishper exited with code 2
whishper                | Error: The directory named as part of the path /var/log/whishper/transcription.out.log does not exist in section 'program:transcription' (file: '/etc/supervisor/conf.d/supervisord.conf')
whishper                | For help, use /usr/bin/supervisord -h
whishper exited with code 2
whishper                | Error: The directory named as part of the path /var/log/whishper/transcription.out.log does not exist in section 'program:transcription' (file: '/etc/supervisor/conf.d/supervisord.conf')
whishper                | For help, use /usr/bin/supervisord -h
whishper exited with code 2
whishper                | Error: The directory named as part of the path /var/log/whishper/transcription.out.log does not exist in section 'program:transcription' (file: '/etc/supervisor/conf.d/supervisord.conf')
whishper                | For help, use /usr/bin/supervisord -h
whishper exited with code 2
whishper                | Error: The directory named as part of the path /var/log/whishper/transcription.out.log does not exist in section 'program:transcription' (file: '/etc/supervisor/conf.d/supervisord.conf')
whishper                | For help, use /usr/bin/supervisord -h
whishper exited with code 2
whishper                | Error: The directory named as part of the path /var/log/whishper/transcription.out.log does not exist in section 'program:transcription' (file: '/etc/supervisor/conf.d/supervisord.conf')
whishper                | For help, use /usr/bin/supervisord -h
whishper exited with code 2
whishper                | Error: The directory named as part of the path /var/log/whishper/transcription.out.log does not exist in section 'program:transcription' (file: '/etc/supervisor/conf.d/supervisord.conf')
whishper                | For help, use /usr/bin/supervisord -h
whishper exited with code 2
whishper                | Error: The directory named as part of the path /var/log/whishper/transcription.out.log does not exist in section 'program:transcription' (file: '/etc/supervisor/conf.d/supervisord.conf')
whishper                | For help, use /usr/bin/supervisord -h
whishper exited with code 2

```

### Docker Compose File

```yaml
version: '3'
services:
  mongo:
    image: mongo
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./whishper_data/db_data:/mnt/user/appdata/whishper/db_data
      - ./whishper_data/db_data/logs:/mnt/user/appdata/whishper/db_data/logs
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER:-whishper}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS:-whishper}
    expose:
      - 27017
    command: ['--logpath', '/var/log/mongodb/mongod.log']

  translate:
    container_name: whisper-libretranslate
    image: libretranslate/libretranslate:latest-cuda
    restart: unless-stopped
    volumes:
      - ./whishper_data/libretranslate/data:/mnt/user/appdata/whishper/db_data/whishper_data/libretranslate/data
      - ./whishper_data/libretranslate/cache:/mnt/user/appdata/whishper/db_data/whishper_data/libretranslate/cache
    env_file:
      - .env
    user: root
    tty: true
    environment:
      LT_DISABLE_WEB_UI: True
      LT_LOAD_ONLY: ${LT_LOAD_ONLY:-en,fr,es}
      LT_UPDATE_MODELS: True
    expose:
      - 5000
    networks:
      default:
        aliases:
          - translate
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]

  whishper:
    pull_policy: always
    image: pluja/whishper:${WHISHPER_VERSION:-latest-gpu}
    env_file:
      - .env
    volumes:
      - ./whishper_data/uploads:/mnt/user/appdata/whishper/uploads
      - ./whishper_data/logs:/mnt/user/appdata/whishper/logs
    container_name: whishper
    restart: unless-stopped
    networks:
      default:
        aliases:
          - whishper
    ports:
      - 8082:80
    depends_on:
      - mongo
      - translate
    environment:
      PUBLIC_INTERNAL_API_HOST: "http://127.0.0.1:80"
      PUBLIC_TRANSLATION_API_HOST: ""
      PUBLIC_API_HOST: ${WHISHPER_HOST:-}
      PUBLIC_WHISHPER_PROFILE: gpu
      WHISPER_MODELS_DIR: /app/models
      UPLOAD_DIR: /app/uploads
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
```
