### ISSUE TITLE
[BUG] Frontend not reacting on start input

### ISSUE THREAD

**Issue by henry4711lp** [pluja/whishper#91]
## **Description**
After clicking "start" under "new transcription" nothing happens

### **To Reproduce**
1. Install on virtualized docker host with script
2. open frontend on X.X.X.X:8082
3. Click "new transcription"
4. Input a link or a file and leave standard values
5. click start
6. nothing happens

### **Expected behavior**
A new transcription should be created like in the presenting screenshots

### Environment
- OS: linux x86_64 Ubuntu 22.04.3 LTS
- Browser: Tested on Arc on Windows/Mac as well as Edge on Windows
- Version: Whishper 3.1.3
- Hosting: Webserver

### Docker Compose Logs

> Run the following command in the project folder, force the error, and paste the logs below: `docker compose logs -f --tail 50`

```
whishper                | 2024-04-19 12:46:04,876 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
whishper                | 2024-04-19 12:46:04,877 INFO supervisord started with pid 1
whishper                | 2024-04-19 12:46:05,879 INFO spawned: 'backend' with pid 6
whishper                | 2024-04-19 12:46:05,880 INFO spawned: 'frontend' with pid 7
whishper                | 2024-04-19 12:46:05,880 INFO spawned: 'nginx' with pid 8
whishper                | 2024-04-19 12:46:05,881 INFO spawned: 'transcription' with pid 9
whishper                | 2024-04-19 12:46:06,978 INFO success: backend entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
whishper                | 2024-04-19 12:46:06,978 INFO success: frontend entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
whishper                | 2024-04-19 12:46:06,978 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
whishper                | 2024-04-19 12:46:06,978 INFO success: transcription entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
whisper-libretranslate  | Updating language models
whisper-libretranslate  | Found 88 models
whisper-libretranslate  | Keep 6 models
whisper-libretranslate  | Downloading English → German (1.0) ...
whisper-libretranslate  | Downloading German → English (1.0) ...
whisper-libretranslate  | Loaded support for 4 languages (6 models total)!
whisper-libretranslate  | Running on http://*:5000
mongo_1                 | {"t":{"$date":"2024-04-19T12:46:04.462Z"},"s":"I",  "c":"CONTROL",  "id":20697,   "ctx":"main","msg":"Renamed existing log file","attr":{"oldLogPath":"/var/log/mongodb/mongod.log","newLogPath":"/var/log/mongodb/mongod.log.2024-04-19T12-46-04"}}
```

### Docker Compose File

```yaml
version: "3.9"

services:
  mongo:
    image: mongo
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./whishper_data/db_data:/data/db
      - ./whishper_data/db_data/logs/:/var/log/mongodb/
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER:-whishper}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS:-whishper}
    expose:
      - 27017
    command: ['--logpath', '/var/log/mongodb/mongod.log']

  translate:
    container_name: whisper-libretranslate
    image: libretranslate/libretranslate:latest
    restart: unless-stopped
    volumes:
      - ./whishper_data/libretranslate/data:/home/libretranslate/.local/share
      - ./whishper_data/libretranslate/cache:/home/libretranslate/.local/cache
    env_file:
      - .env
    tty: true
    environment:
      LT_DISABLE_WEB_UI: 'True'
      LT_UPDATE_MODELS: 'True'
    expose:
      - 5000
    networks:
      default:
        aliases:
          - translate
    healthcheck:
      test: ['CMD-SHELL', './venv/bin/python scripts/healthcheck.py']
      interval: 2s
      timeout: 3s
      retries: 5

  whishper:
    pull_policy: always
    image: pluja/whishper:${WHISHPER_VERSION:-latest}
    env_file:
      - .env
    volumes:
      - ./whishper_data/uploads:/app/uploads
      - ./whishper_data/logs:/var/log/whishper
    container_name: whishper
    restart: unless-stopped
    networks:
      default:
        aliases:
          - whishper
    ports:
      - 8082:80
    depends_on:
      - mongo
      - translate
    environment:
      PUBLIC_INTERNAL_API_HOST: "http://127.0.0.1:80"
      PUBLIC_TRANSLATION_API_HOST: ""
      PUBLIC_API_HOST: ${WHISHPER_HOST:-}
      PUBLIC_WHISHPER_PROFILE: cpu
      WHISPER_MODELS_DIR: /app/models
      UPLOAD_DIR: /app/uploads
      CPU_THREADS: 4
```
